const shops=[
{id:1,tier:'current',name:'오늘의 반찬상',cat:'반찬·식품',desc:'매일 아침 만드는 가정식 반찬과 도시락',price:'대표 반찬 6,000원',benefit:'우리 단지 1,000원 할인',action:'주문 관심',img:'https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=900&q=80'},
{id:2,tier:'current',name:'맑은집 홈케어',cat:'청소·수리',desc:'에어컨과 세탁기 분해 청소 방문 서비스',price:'상담 후 견적',benefit:'출장비 무료',action:'견적 요청',img:'https://images.unsplash.com/photo-1581578731548-c64695cc6952?auto=format&fit=crop&w=900&q=80'},
{id:3,tier:'current',name:'차분한 수학',cat:'과외·수업',desc:'초등·중등 수학 소수정예 방문 수업',price:'월 180,000원부터',benefit:'첫 상담 무료',action:'상담 요청',img:'https://images.unsplash.com/photo-1509062522246-3755977927d7?auto=format&fit=crop&w=900&q=80'},
{id:4,tier:'neighbor',name:'골목 베이크룸',cat:'카페·디저트',desc:'이웃 단지 주민이 굽는 소량 예약 베이커리',price:'스콘 3,500원',benefit:'4개 구매 시 1개 추가',action:'예약 요청',img:'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=900&q=80'},
{id:5,tier:'neighbor',name:'온결 헤어룸',cat:'뷰티·운동',desc:'예약제로 운영하는 1인 헤어 스튜디오',price:'커트 18,000원',benefit:'첫 방문 10% 할인',action:'예약 요청',img:'https://images.unsplash.com/photo-1560066984-138dadb4c035?auto=format&fit=crop&w=900&q=80'},
{id:6,tier:'neighbor',name:'포근펫 케어',cat:'반려동물',desc:'산책, 방문 돌봄, 병원 동행 서비스',price:'30분 12,000원',benefit:'첫 이용 2,000원 할인',action:'상담 요청',img:'https://images.unsplash.com/photo-1552053831-71594a27632d?auto=format&fit=crop&w=900&q=80'},
{id:7,tier:'local',name:'작은정원 플라워',cat:'꽃·선물',desc:'꽃다발, 화병꽂이, 소규모 원데이 클래스',price:'꽃다발 25,000원부터',benefit:'단지 수령 무료',action:'주문 관심',img:'https://images.unsplash.com/photo-1490750967868-88aa4486c946?auto=format&fit=crop&w=900&q=80'},
{id:8,tier:'local',name:'동네 사진관',cat:'사진·디자인',desc:'증명사진과 가족사진 예약 촬영',price:'증명사진 20,000원',benefit:'가족사진 액자 증정',action:'예약 요청',img:'https://images.unsplash.com/photo-1542038784456-1ea8e935640e?auto=format&fit=crop&w=900&q=80'},
{id:9,tier:'local',name:'푸드마켓 반찬',cat:'반찬·식품',desc:'소포장 반찬과 국을 판매하는 동네 식품점',price:'반찬 5,000원부터',benefit:'3만원 이상 배달 무료',action:'주문 관심',img:'https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=900&q=80'},
{id:10,tier:'current',availability:'suspended',name:'단비 세탁소',cat:'청소·수리',desc:'운영 일시 중지 중인 합성 예시 업체',price:'이용 불가',benefit:'운영 재개 예정 · 합성',action:'이용 불가',img:'https://images.unsplash.com/photo-1582735689369-4fe89db7114c?auto=format&fit=crop&w=900&q=80'}
];
const tiers={current:{label:'방림명지로드힐 주민 운영',short:'우리 단지 주민',title:'1순위 우리 아파트 주민의 가게와 서비스'},neighbor:{label:'이웃 단지 주민 운영',short:'이웃 단지 주민',title:'2순위 이웃 아파트 주민의 가게와 서비스'},local:{label:'우리 동네 가게',short:'동네 가게',title:'3순위 우리 동네 가게'}};
const state={route:'home',role:'resident',tier:'all',query:'',selected:1,favs:new Set(),requests:[],step:1,ownerStatus:'draft',decision:'',registration:{tier:'current',name:'우리집 정리수납',desc:'정리수납과 이사 전후 공간 정돈을 돕는 방문 서비스',price:'2시간 60,000원',benefit:'우리 단지 상담 무료'}};
const $=s=>document.querySelector(s), pages=[...document.querySelectorAll('.page')], toast=$('#toast'), backdrop=$('#modalBackdrop'), modalTitle=$('#modalTitle'), modalBody=$('#modalBody'), modalConfirm=$('#modalConfirm');let confirmFn=null;
function badge(t){return `<span class="tier-label ${t}">${tiers[t].label}</span>`}
function shell(x){return `<div class="wrap">${x}</div>`}
function card(x){const fav=state.favs.has(x.id);const susp=x.availability==='suspended';return `<article class="listing-card${susp?' suspended':''}" data-open="${x.id}">${susp?'<span class="suspended-badge">이용 불가 · 합성</span>':''}<img class="listing-photo" src="${x.img}" alt="${x.name} 합성 예시"><button type="button" class="favorite ${fav?'active':''}" data-fav="${x.id}"${susp?' disabled':''} aria-label="${susp?'이용 불가 · 찜 불가':'찜하기'}">${fav?'♥':'♡'}</button><div class="copy">${badge(x.tier)}<h3>${x.name}</h3><p>${x.desc}</p><div class="benefit">${x.benefit}</div><div class="listing-meta"><strong>${x.price}</strong><span>${susp?'이용 불가':'데모 정보'}</span></div></div></article>`}
function hero(){return `<div class="location"><div><h1>방림명지로드힐 ▾</h1><p>광주 남구 · 192세대 · 합성 예시 업체</p></div></div><div class="hero"><section class="lead"><span class="eyebrow">주민이 주민을 먼저 돕는 생활경제</span><h2>우리 이웃이 하는 일을 먼저 찾고, 함께 이용해요.</h2><p>가게뿐 아니라 과외·청소·전문서비스·온라인 판매까지 우리 단지 주민의 일을 가장 먼저 보여줍니다.</p><div class="actions"><button class="primary" type="button" data-route="explore">이웃가게 둘러보기</button><button class="secondary" type="button" data-role="owner">내 일 등록 데모</button></div></section><aside class="priority"><h3>기본 노출 순서</h3><div class="priority-row"><b>1</b><div><strong>우리 단지 주민</strong><span>방림명지로드힐 주민 운영</span></div></div><div class="priority-row"><b>2</b><div><strong>이웃 단지 주민</strong><span>주변 공동주택 주민 운영</span></div></div><div class="priority-row"><b>3</b><div><strong>동네 가게</strong><span>일반 주변 업체</span></div></div><div class="compact-priority"><span><b>1</b>우리 단지</span><span><b>2</b>이웃 단지</span><span><b>3</b>동네 가게</span></div></aside></div>`}
function search(){return `<div class="search-panel"><div class="search-box"><input data-search-input value="${state.query}" placeholder="반찬, 수학, 에어컨 청소를 검색해보세요"><select data-search-tier><option value="all">관계 우선 전체</option><option value="current" ${state.tier==='current'?'selected':''}>우리 단지 주민</option><option value="neighbor" ${state.tier==='neighbor'?'selected':''}>이웃 단지 주민</option><option value="local" ${state.tier==='local'?'selected':''}>동네 가게</option></select><button type="button" data-action="search">⌕</button></div></div>`}
function home(){return shell(`${hero()}${search()}<section class="section"><div class="section-head"><div><h2>무엇을 찾고 있나요?</h2><p>방문 서비스와 전문 업무도 함께 찾을 수 있어요.</p></div></div><div class="categories">${['전체','반찬·식품','카페·디저트','청소·수리','과외·수업','뷰티·운동','반려동물','사진·디자인'].map((x,i)=>`<button class="category" type="button" data-query="${i?x:''}"><span>${['⌘','🍱','☕','🧹','✎','✂','🐾','▣'][i]}</span><b>${x}</b></button>`).join('')}</div></section>${['current','neighbor','local'].map(t=>`<section class="section"><div class="section-head"><div><h2>${tiers[t].title}</h2><p>${t==='current'?'현재 단지 주민의 경제활동을 가장 먼저 소개합니다.':t==='neighbor'?'현재 단지에 없는 업종을 이웃 단지 주민이 보완합니다.':'주민 업체 다음에 확인하는 일반 주변 업체입니다.'}</p></div><button type="button" data-tier="${t}">전체 보기</button></div><div class="listing-grid">${shops.filter(x=>x.tier===t).map(card).join('')}</div></section>`).join('')}`)}
function filtered(){const q=state.query.toLowerCase();return shops.filter(x=>(state.tier==='all'||x.tier===state.tier)&&(!q||`${x.name} ${x.cat} ${x.desc}`.toLowerCase().includes(q)))}
function explore(){const rows=filtered();return shell(`<div class="page-title"><div class="crumb">홈 · 탐색</div><h1>가게와 서비스 찾기</h1><p>검색어보다 주민 관계 순서를 먼저 유지합니다.</p></div>${search()}<div class="filter-row">${['all','current','neighbor','local'].map(t=>`<button type="button" data-tier="${t}" class="${state.tier===t?'active':''}">${t==='all'?'전체':tiers[t].short}</button>`).join('')}</div><section class="section">${rows.length?['current','neighbor','local'].map(t=>{const a=rows.filter(x=>x.tier===t);return a.length?`<div class="result-group"><div class="result-title"><h2>${tiers[t].title}</h2><span>${a.length}개</span></div><div class="listing-grid">${a.map(card).join('')}</div></div>`:''}).join(''):`<div class="empty"><h3>검색 결과가 없습니다</h3><p>다른 검색어로 데모를 확인하세요.</p><button class="secondary" type="button" data-action="clear">검색 초기화</button></div>`}</section>`)}
function detail(){const x=shops.find(v=>v.id===state.selected)||shops[0];const susp=x.availability==='suspended';const reqBtn=susp?'<button class="primary" type="button" disabled>현재 이용 불가</button><p class="suspended-copy">이용이 중지된 합성 예시 업체입니다. 문의·예약·주문은 실행되지 않습니다.</p>':'<button class="primary" type="button" data-request="'+x.action+'">'+x.action+'</button>';return shell(`<div class="page-title"><div class="crumb">탐색 · ${x.cat}</div><h1>${x.name}</h1><p>모든 정보와 관계 배지는 합성 예시입니다.</p></div>${susp?'<div class="suspended-notice"><strong>현재 이용 불가 · 운영 일시 중지</strong><p>합성 예시로 운영이 일시 중지된 업체입니다. 요청·예약·주문이 실제로 실행되지 않습니다.</p></div>':''}<div class="detail-layout"><article class="detail-main"><div class="gallery"><img src="${x.img}" alt="${x.name} 예시"><div class="gallery-side"><img src="${x.img}" alt="예시 사진"><img src="${x.img}" alt="예시 사진"></div></div><div class="detail-copy">${badge(x.tier)}<h1>${x.name}</h1><p>${x.desc}</p><div class="detail-section"><h2>대표 서비스</h2><div class="offer"><div><strong>${x.cat} 기본 서비스</strong><br><span>상세 조건은 데모 문구입니다.</span></div><b>${x.price}</b></div><div class="offer"><div><strong>주민 혜택</strong><br><span>관계와 혜택은 별도 정보입니다.</span></div><b>${x.benefit}</b></div></div></div></article><aside class="detail-side"><section class="side-card notice"><strong>클릭 데모</strong><h2>${x.benefit}</h2><p>버튼을 눌러도 실제 요청은 전송되지 않습니다.</p></section><section class="side-card"><h2>${x.price}</h2><div class="side-actions">${reqBtn}<button class="secondary" type="button" data-fav="${x.id}">${state.favs.has(x.id)?'찜 해제':'찜하기'}</button></div></section><section class="side-card"><h2>주민 운영 확인</h2><p>관리주체의 추천이나 서비스 품질 보증을 뜻하지 않습니다.</p></section></aside></div>`)}
function benefits(){return shell(`<div class="page-title"><div class="crumb">홈 · 혜택</div><h1>우리 이웃이 준비한 주민 혜택</h1><p>관계 라벨과 할인 혜택을 구분합니다.</p></div><div class="benefit-grid">${shops.map(x=>`<article class="benefit-card"><img src="${x.img}" alt="${x.name} 예시"><div><small class="relation ${x.tier}">${tiers[x.tier].label}</small><h3>${x.name}</h3><p>${x.benefit}</p><button class="secondary" type="button" data-open="${x.id}">상세 보기</button></div></article>`).join('')}</div>`)}
function saved(){const favs=shops.filter(x=>state.favs.has(x.id));return shell(`<div class="page-title"><div class="crumb">내 데모 기록</div><h1>찜과 요청 내역</h1><p>브라우저 메모리에만 존재하며 새로고침하면 초기화됩니다.</p></div><section class="section"><div class="section-head"><div><h2>찜한 가게와 서비스</h2><p>${favs.length}개</p></div></div>${favs.length?`<div class="listing-grid">${favs.map(card).join('')}</div>`:`<div class="empty"><h3>찜한 곳이 없습니다</h3><button class="secondary" type="button" data-route="explore">둘러보기</button></div>`}</section><section class="section"><div class="section-head"><div><h2>보낸 요청</h2><p>실제 전송되지 않은 데모 기록</p></div></div>${state.requests.length?`<div class="panel"><table class="table"><thead><tr><th>가게</th><th>요청</th><th>상태</th></tr></thead><tbody>${state.requests.map(r=>`<tr><td>${r.name}</td><td>${r.type}</td><td><span class="status review">데모 접수</span></td></tr>`).join('')}</tbody></table></div>`:`<div class="empty"><h3>보낸 요청이 없습니다</h3><p>상세 화면에서 요청 데모를 실행하세요.</p></div>`}</section>`)}
function ownerNav(a){return `<aside class="side-nav"><button class="${a==='dash'?'active':''}" type="button" data-route="owner-dashboard">내 가게 관리</button><button class="${a==='reg'?'active':''}" type="button" data-route="owner-register">가게 등록</button><button class="${a==='preview'?'active':''}" type="button" data-route="owner-preview">공개 미리보기</button><button type="button" data-role="resident">주민 화면</button></aside>`}
function ownerDashboard(){return shell(`<div class="page-title"><div class="crumb">사업자 데모 모드</div><h1>내 가게 관리</h1><p>실제 계정이나 권한이 아닙니다.</p></div><div class="dashboard">${ownerNav('dash')}<section class="panel"><h2>${state.registration.name}</h2><p>검토 상태와 합성 문의를 확인합니다.</p><div class="metric-row"><div class="metric"><span>검토 상태</span><b>${state.ownerStatus}</b></div><div class="metric"><span>합성 문의</span><b>3</b></div><div class="metric"><span>찜</span><b>12</b></div><div class="metric"><span>공개</span><b>${state.ownerStatus==='approved'?'예시 공개':'비공개'}</b></div></div><div class="form-actions"><button class="secondary" type="button" data-route="owner-register">정보 수정</button><button class="primary" type="button" data-route="owner-preview">미리보기</button></div></section></div>`)}
function ownerRegister(){const r=state.registration;let body;if(state.step===1)body=`<h2>1. 주민 관계 선택</h2><p>업종보다 주민 관계를 먼저 선택합니다.</p><div class="choice-grid">${['current','neighbor','local'].map(t=>`<button class="choice ${r.tier===t?'active':''}" type="button" data-regtier="${t}"><strong>${tiers[t].short}</strong><span>${tiers[t].label}</span></button>`).join('')}</div>`;else if(state.step===2)body=`<h2>2. 기본 정보</h2><p>입력값은 실제 저장되지 않습니다.</p><div class="form-grid"><div class="field"><label>이름<input id="regName" value="${r.name}"></label></div><div class="field"><label>대표 가격<input id="regPrice" value="${r.price}"></label></div><div class="field full"><label>한 줄 소개<textarea id="regDesc">${r.desc}</textarea></label></div><div class="field full"><label>주민 혜택<input id="regBenefit" value="${r.benefit}"></label></div></div>`;else body=`<h2>3. 검토 요청 확인</h2><p>제출 버튼은 상태만 바꾸며 실제 전송되지 않습니다.</p><div class="panel">${badge(r.tier)}<h2>${r.name}</h2><p>${r.desc}</p><strong>${r.price}</strong><div class="benefit">${r.benefit}</div></div>`;return shell(`<div class="page-title"><div class="crumb">사업자 데모 · 등록</div><h1>가게와 서비스 등록</h1><p>새로고침하면 모든 상태가 초기화됩니다.</p></div><div class="dashboard">${ownerNav('reg')}<section class="panel"><div class="stepper"><span class="active"></span><span class="${state.step>1?'active':''}"></span><span class="${state.step>2?'active':''}"></span></div>${body}<div class="form-actions"><button class="secondary" type="button" data-action="prev">이전</button>${state.step<3?'<button class="primary" type="button" data-action="next">다음</button>':'<button class="primary" type="button" data-action="submit">검토 요청 데모</button>'}</div></section></div>`)}
function ownerPreview(){const r=state.registration;return shell(`<div class="page-title"><div class="crumb">사업자 데모 · 미리보기</div><h1>게시 전 미리보기</h1><p>운영자 승인 전에는 실제 공개되지 않는다는 원칙을 보여줍니다.</p></div><div class="dashboard">${ownerNav('preview')}<section class="panel"><div class="listing-grid"><article class="listing-card"><img class="listing-photo" src="https://images.unsplash.com/photo-1527515637462-cff94eecc1ac?auto=format&fit=crop&w=900&q=80" alt="정리수납 합성 예시"><div class="copy">${badge(r.tier)}<h3>${r.name}</h3><p>${r.desc}</p><div class="benefit">${r.benefit}</div><div class="listing-meta"><strong>${r.price}</strong><span>${state.ownerStatus}</span></div></div></article></div><div class="form-actions"><button class="secondary" type="button" data-route="owner-register">수정</button><button class="primary" type="button" data-action="submit">검토 요청</button></div></section></div>`)}
function opNav(a){return `<aside class="side-nav"><button class="${a==='queue'?'active':''}" type="button" data-route="operator-queue">검토 대기</button><button class="${a==='review'?'active':''}" type="button" data-route="operator-review">검토 상세</button><button type="button" data-role="resident">주민 화면</button></aside>`}
function operatorQueue(){return shell(`<div class="page-title"><div class="crumb">운영자 데모 모드</div><h1>검토 대기 목록</h1><p>실제 운영 권한이나 주민 증빙 접근이 없는 시뮬레이션입니다.</p></div><div class="dashboard">${opNav('queue')}<section class="panel"><h2>검토 대기 3건</h2><table class="table"><thead><tr><th>이름</th><th>관계 요청</th><th>상태</th><th></th></tr></thead><tbody><tr><td>우리집 정리수납</td><td>우리 단지 주민</td><td><span class="status review">검토 중</span></td><td><button class="secondary" type="button" data-route="operator-review">검토</button></td></tr><tr><td>차분한 코딩수업</td><td>이웃 단지 주민</td><td><span class="status changes">수정 요청</span></td><td><button class="secondary" type="button" data-action="demo">보기</button></td></tr><tr><td>모닝샐러드</td><td>동네 가게</td><td><span class="status draft">신규</span></td><td><button class="secondary" type="button" data-action="demo">보기</button></td></tr></tbody></table></section></div>`)}
function operatorReview(){const r=state.registration;return shell(`<div class="page-title"><div class="crumb">운영자 데모 · 검토 상세</div><h1>${r.name} 검토</h1><p>주민 운영 확인은 품질 보증이나 관리주체 추천이 아닙니다.</p></div><div class="dashboard">${opNav('review')}<div class="review-layout"><section class="review-preview">${badge(r.tier)}<h2>${r.name}</h2><p>${r.desc}</p><div class="notice" style="padding:13px;border-radius:10px"><strong>비공개 증빙은 이 데모에 존재하지 않습니다.</strong><p>실제 제품에서는 공개 정보와 증빙 접근 권한을 분리합니다.</p></div></section><aside class="review-controls"><h2>운영자 결정 데모</h2><label class="field"><span>사업자에게 공개되는 사유</span><textarea>서비스 지역을 더 명확히 적어주세요.</textarea></label><label class="field"><span>내부 메모 자리표시자</span><textarea>실제 증빙이나 개인정보는 기록하지 않습니다.</textarea></label><div class="review-actions"><button class="primary" type="button" data-decision="approved">승인 데모</button><button class="secondary" type="button" data-decision="changes_requested">수정 요청</button><button class="danger" type="button" data-decision="rejected">거절 데모</button></div>${state.decision?`<p><span class="status review">결정: ${state.decision}</span></p>`:''}</aside></div></div>`)}
const views={home,explore,detail,benefits,saved,'owner-dashboard':ownerDashboard,'owner-register':ownerRegister,'owner-preview':ownerPreview,'operator-queue':operatorQueue,'operator-review':operatorReview};
function render(){pages.forEach(p=>p.classList.remove('active'));const p=document.querySelector(`[data-page="${state.route}"]`);p.innerHTML=views[state.route]();p.classList.add('active');document.querySelectorAll('[data-route]').forEach(x=>x.classList.toggle('active',x.dataset.route===state.route));document.querySelectorAll('[data-role]').forEach(x=>x.classList.toggle('active',x.dataset.role===state.role));bindInputs()}
function route(r){state.route=r;render();scrollTo({top:0,behavior:'smooth'})}
function say(x){toast.textContent=x;toast.classList.add('show');clearTimeout(say.t);say.t=setTimeout(()=>toast.classList.remove('show'),2600)}
function modal(title,html,fn){modalTitle.textContent=title;modalBody.innerHTML=html;confirmFn=fn;backdrop.classList.add('open')}
function closeModal(){backdrop.classList.remove('open');confirmFn=null}
function role(r){state.role=r;route(r==='resident'?'home':r==='owner'?'owner-dashboard':'operator-queue');say(`${r==='resident'?'주민':r==='owner'?'사업자':'운영자'} 데모 모드입니다. 실제 인증이 아닙니다.`)}
function bindInputs(){const p=document.querySelector(`[data-page="${state.route}"]`);const q=p&&p.querySelector('[data-search-input]');if(q)q.addEventListener('keydown',e=>{if(e.key==='Enter'){state.query=q.value;route('explore')}});const t=p&&p.querySelector('[data-search-tier]');if(t)t.addEventListener('change',()=>{state.tier=t.value;route('explore')});[['regName','name'],['regPrice','price'],['regDesc','desc'],['regBenefit','benefit']].forEach(([id,k])=>{const el=p&&p.querySelector('#'+id);if(el)el.addEventListener('input',()=>state.registration[k]=el.value)})}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.route)return route(b.dataset.route);if(b.dataset.role)return role(b.dataset.role);if(b.dataset.open){state.selected=+b.dataset.open;return route('detail')}if(b.dataset.fav){const id=+b.dataset.fav;state.favs.has(id)?state.favs.delete(id):state.favs.add(id);say(state.favs.has(id)?'찜 데모에 추가했습니다.':'찜 데모에서 제거했습니다.');return render()}if(b.dataset.tier){state.tier=b.dataset.tier;return route('explore')}if(b.dataset.query!==undefined){state.query=b.dataset.query;return route('explore')}if(b.dataset.regtier){state.registration.tier=b.dataset.regtier;return render()}if(b.dataset.request){const x=shops.find(v=>v.id===state.selected);return modal(b.dataset.request,`<p><strong>${x.name}</strong>에 보내는 합성 요청입니다.</p><label class="field"><span>요청 내용</span><textarea>가능한 시간과 조건을 알려주세요.</textarea></label><p>확인을 눌러도 실제로 전송되거나 저장되지 않습니다.</p>`,()=>{state.requests.push({name:x.name,type:b.dataset.request});closeModal();say('데모 요청을 표시했습니다. 실제 전송은 없습니다.');route('saved')})}if(b.dataset.decision){state.decision=b.dataset.decision;state.ownerStatus=b.dataset.decision;say('운영자 결정 데모를 반영했습니다. 실제 승인이나 권한 변경은 없습니다.');return render()}const a=b.dataset.action;if(a==='search'){const box=b.closest('.search-box');state.query=(box&&box.querySelector('[data-search-input]'))?.value||'';route('explore')}if(a==='clear'){state.query='';state.tier='all';render()}if(a==='next'){state.step=Math.min(3,state.step+1);render()}if(a==='prev'){state.step=Math.max(1,state.step-1);render()}if(a==='submit'){state.ownerStatus='under_review';say('검토 요청 데모 상태로 바꿨습니다. 실제 전송은 없습니다.');route('owner-dashboard')}if(a==='demo')say('설명용 버튼입니다. 실제 데이터나 권한은 없습니다.');if(a==='reset-demo'){state.favs.clear();state.requests=[];state.query='';state.tier='all';state.step=1;state.ownerStatus='draft';state.decision='';say('데모 상태를 초기화했습니다.');route('home')}if(a==='open-role')modal('데모 모드 선택','<p>실제 로그인이나 권한이 아닙니다.</p><div class="choice-grid"><button class="choice" type="button" data-role="resident"><strong>주민</strong></button><button class="choice" type="button" data-role="owner"><strong>사업자</strong></button><button class="choice" type="button" data-role="operator"><strong>운영자</strong></button></div>',closeModal);if(a==='close-modal')closeModal()});
modalConfirm.addEventListener('click',()=>confirmFn?confirmFn():closeModal());backdrop.addEventListener('click',e=>{if(e.target===backdrop)closeModal()});document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal()});render();
