"""Padiem AI Core package entrypoint."""

from __future__ import annotations

import importlib

from .contracts import (
    AgentProfile,
    ApprovalPolicy,
    ErrorClass,
    Evidence,
    RunMetadata,
    RunStatus,
    ToolEvent,
    ToolSideEffect,
    ToolSpec,
    UsageMetadata,
)
from .web_runtime import (
    FIRECRAWL_ORIGIN,
    MAX_PROVIDER_RESPONSE_BYTES,
    MAX_QUERY_CHARS,
    MAX_RESULTS,
    MAX_SNIPPET_CHARS,
    MAX_TITLE_CHARS,
    MAX_URL_CHARS,
    FirecrawlWebProvider,
    MockWebProvider,
    OffWebProvider,
    WebProvider,
    WebRuntimeConfig,
    WebRuntimeError,
    create_web_provider,
    normalize_public_url,
)
from .b14_execution import (
    B14_CHAT_COMPLETIONS_PATH,
    MAX_B14_RESPONSE_BYTES,
    B14ChatRequest,
    B14ExecutionClient,
    B14ExecutionConfig,
    B14ExecutionError,
    B14ExecutionResult,
    B14RouteMetadata,
    B14RoutingOptions,
)
from .b14_multimodal import (
    B14MultimodalChatRequest,
    MAX_B14_IMAGE_BYTES,
    MAX_B14_MULTIMODAL_PARTS,
)
from .b14_transport import (
    B14PostJSONTransport,
    B14Transport,
    B14TransportResponse,
)
from .b14_streaming import (
    B14_STREAM_PREVIEW_PATH,
    B14StreamEvent,
    B14StreamingClient,
)
from .grounding_runtime import (
    DEFAULT_GROUNDING_PREAMBLE,
    MAX_GROUNDED_EVIDENCE_CONTEXT_CHARS,
    MAX_GROUNDED_SOURCES,
    MAX_RESEARCH_PAGE_FETCHES,
    MAX_RESEARCH_QUERIES,
    MAX_RESEARCH_SOURCES,
    GroundedResearchResult,
    GroundedResearchRuntime,
    GroundedSynthesisResult,
    GroundingPolicy,
    GroundingRuntimeError,
    PreparedGrounding,
    ResearchProgress,
    dedupe_evidence,
    parse_research_queries,
    prepare_combined_grounding_context,
    prepare_grounding_context,
)
from .execution_runtime import (
    MAX_ADDITIONAL_SYSTEM_CONTEXT_CHARS,
    MAX_COMPOSED_SYSTEM_CHARS,
    MAX_EXECUTION_MESSAGE_CHARS,
    MAX_EXECUTION_MESSAGES,
    B14Executor,
    ExecutionRequest,
    ExecutionResult,
    ExecutionRuntime,
    ExecutionRuntimeError,
)
from .streaming_runtime import (
    B14StreamExecutor,
    StreamingExecutionEvent,
    StreamingExecutionRuntime,
)
from .execution_context import (
    ExecutionContext,
    IdempotencyAdapter,
    IdempotencyConflictError,
    request_fingerprint,
)
from .contextual_execution import (
    ContextualExecutionRunner,
    PreparedExecution,
    prepare_execution,
)
from .retrieval import (
    MAX_RETRIEVAL_NAMESPACES,
    MAX_RETRIEVAL_RESULTS,
    PreparedRetrieval,
    RetrievalContractError,
    RetrievalPolicy,
    RetrievalProvider,
    RetrievalRequest,
    RetrievedItem,
    prepare_retrieval_context,
)
from .memory import (
    MAX_MEMORY_APPROVED_PROPOSALS,
    MAX_MEMORY_AUTH_NAMESPACES,
    MAX_MEMORY_CONTENT_CHARS,
    MAX_MEMORY_DERIVED_FROM,
    MAX_MEMORY_SOURCE_REF_CHARS,
    MemoryContractError,
    MemoryNamespace,
    MemoryProvenance,
    MemoryScope,
    MemoryWriteAuthorization,
    MemoryWriteOrigin,
    MemoryWritePolicy,
    MemoryWriteRequest,
    PreparedMemoryWrite,
    authorize_memory_write,
)
from .memory_read import (
    MemoryReadAuthorization,
    MemoryReadPolicy,
    authorize_memory_retrieval,
)
from .memory_receipt import (
    IdempotentMemoryWriteAdapter,
    MemoryWriteDisposition,
    MemoryWriteReceipt,
    persist_authorized_memory_write,
    validate_memory_write_receipt,
)
from .memory_context import (
    RankedMemoryItem,
    RetrievalScore,
    assemble_long_context,
    rank_retrieval_results,
)
from .agent_approval import (
    AgentApprovalError,
    AgentContinuationState,
    ApprovalOutcome,
    ApprovalPause,
    ApprovalRequirement,
    ContinuationStatus,
    VerifiedApprovalDecision,
    approval_pause_from_tool_error,
    resolve_approval_pause,
    assert_same_invocation,
    tool_invocation_digest,
)
from .agent_definition import (
    MAX_APPROVAL_CHECKPOINTS,
    MAX_CAPABILITIES,
    MAX_CONNECTOR_IDS,
    MAX_DESCRIPTION_CHARS,
    MAX_INSTRUCTION_CHARS,
    MAX_SKILL_IDS,
    MAX_TOOL_IDS,
    AgentApprovalCheckpoint,
    AgentDefinitionError,
    AgentExecutionBudget,
    AgentTerminalReason,
    BoundedAgentDefinition,
    missing_agent_capabilities,
)
from .agent_profile_adapter import (
    AgentProfileCompilationError,
    CompiledAgentProfile,
    ToolRuntimeBinding,
    TrustedAgentRuntimePolicy,
    compile_agent_profile,
)
from .agent_planner import (
    MAX_AGENT_PLAN_DEPENDENCIES,
    MAX_AGENT_PLAN_INPUT_CHARS,
    MAX_AGENT_PLAN_OBJECTIVE_CHARS,
    MAX_AGENT_PLAN_STEPS,
    AgentPlan,
    AgentPlanStep,
    AgentPlanner,
    AgentPlannerError,
    validate_agent_plan,
    validate_agent_plan_input,
)
from .agent_recovery import (
    AgentFailure,
    AgentFailureSource,
    AgentRecoveryAction,
    AgentRecoveryContext,
    AgentRecoveryDecision,
    AgentRecoveryError,
    AgentRecoveryPolicy,
    decide_agent_recovery,
)
from .agent_delegation import (
    AgentDelegationError,
    AgentDelegationRequest,
    DelegatedAgentAuthority,
    authorize_agent_delegation,
    delegation_fingerprint,
)
from .agent_events import (
    AgentEvent,
    AgentEventError,
    AgentEventKind,
    public_agent_event,
)
from .skill_package import (
    ApprovalHook,
    MAX_ALLOWED_TOOLS,
    MAX_APPROVAL_HOOKS,
    MAX_CONNECTOR_REQUIREMENTS,
    MAX_REQUIRED_CAPABILITIES,
    ReusableSkillPackage,
    SkillPackageError,
    missing_required_capabilities,
)
from .skill_versioning import (
    SkillCompatibility,
    SkillCompatibilityDecision,
    SkillMigrationMap,
    SkillVersionError,
    evaluate_skill_compatibility,
    parse_skill_major,
)
from .skill_registry import (
    SkillInstallation,
    SkillInstallationSnapshot,
    SkillInstallStatus,
    SkillRegistryError,
    SkillRegistrySnapshot,
    resolve_enabled_skill,
)
from .skill_activation import (
    ActivatedSkillProfile,
    compile_enabled_skill,
)
from .skill_runtime_adapter import (
    CompiledSkillProfile,
    SkillRuntimeAdapterError,
    TrustedSkillRuntimePolicy,
    compile_skill_profile,
)
from .tool_registry import (
    MAX_REGISTERED_TOOLS,
    ToolRegistryError,
    ToolRegistrySnapshot,
)
from .connector_registry import (
    ConnectorDescriptor,
    ConnectorRegistryError,
    ConnectorRegistrySnapshot,
    MAX_CONNECTOR_TOOLS,
    MAX_REGISTERED_CONNECTORS,
)
from .tool_resource_policy import (
    EffectiveToolResources,
    ToolResourcePolicy,
    ToolResourcePolicyError,
    resolve_tool_resources,
)
from .tool_lifecycle import (
    ConnectorLifecycleEvent,
    ConnectorLifecycleKind,
    ToolLifecycleError,
    ToolLifecycleEvent,
    ToolLifecycleKind,
)
from .evidence_graph import (
    ClaimDerivation,
    ClaimEvidenceLink,
    ClaimEvidenceRelation,
    EvidenceClaim,
    EvidenceGraph,
    EvidenceGraphError,
    evidence_graph,
)
from .evidence_verification import (
    AcceptedVerification,
    EvidenceValidator,
    EvidenceVerificationError,
    MAX_ALLOWED_VALIDATORS,
    MAX_VERIFICATION_EVIDENCE_IDS,
    MAX_VERIFICATION_SUMMARY_CHARS,
    TrustedVerificationPolicy,
    VerificationDisposition,
    VerificationRequest,
    VerificationVerdict,
    accept_verification_verdict,
)
from .evidence_citation import (
    EvidenceCitationError,
    GroundedCitation,
    GroundedCitationBundle,
    MAX_CITATIONS_PER_CLAIM,
    project_grounded_citations,
)
from .evidence_assessment import (
    ClaimAssessment,
    ClaimAssessmentState,
    EvidenceAssessmentError,
    MAX_ASSESSMENT_EVIDENCE_IDS,
    assess_claim,
    is_verification_satisfied,
)

from .orchestration_events import (
    OrchestrationEvent,
    OrchestrationEventError,
    OrchestrationEventKind,
    public_orchestration_event,
)
from .orchestration import (
    OrchestrationError,
    OrchestrationRequest,
    OrchestrationResult,
    OrchestrationRunner,
)

_TOOL_RUNTIME_EXPORTS = frozenset(
    {
        "OrchestrationEvent",
    "OrchestrationEventError",
    "OrchestrationEventKind",
    "public_orchestration_event",
    "OrchestrationError",
    "OrchestrationRequest",
    "OrchestrationResult",
    "OrchestrationRunner",
    "MAX_TOOL_ARGUMENT_BYTES",
        "MAX_TOOL_OUTPUT_BYTES",
        "ToolAuthorizationContext",
        "ToolExecutionResult",
        "ToolHandler",
        "ToolInvocation",
        "ToolRuntime",
        "ToolRuntimeError",
    }
)


def __getattr__(name: str):
    if name not in _TOOL_RUNTIME_EXPORTS:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    try:
        module = importlib.import_module(".tool_runtime", __name__)
    except ModuleNotFoundError as exc:
        if exc.name == "jsonschema":
            raise ImportError(
                "Tool Runtime requires the optional 'tools' dependency: "
                "install padiem-ai-core[tools]."
            ) from exc
        raise
    value = getattr(module, name)
    globals()[name] = value
    return value


__all__ = [
    "AgentProfile",
    "ApprovalPolicy",
    "ErrorClass",
    "Evidence",
    "RunMetadata",
    "RunStatus",
    "ToolEvent",
    "ToolSideEffect",
    "ToolSpec",
    "UsageMetadata",
    "FIRECRAWL_ORIGIN",
    "MAX_PROVIDER_RESPONSE_BYTES",
    "MAX_QUERY_CHARS",
    "MAX_RESULTS",
    "MAX_SNIPPET_CHARS",
    "MAX_TITLE_CHARS",
    "MAX_URL_CHARS",
    "FirecrawlWebProvider",
    "MockWebProvider",
    "OffWebProvider",
    "WebProvider",
    "WebRuntimeConfig",
    "WebRuntimeError",
    "create_web_provider",
    "normalize_public_url",
    "B14_CHAT_COMPLETIONS_PATH",
    "MAX_B14_RESPONSE_BYTES",
    "B14ChatRequest",
    "B14ExecutionClient",
    "B14ExecutionConfig",
    "B14ExecutionError",
    "B14ExecutionResult",
    "B14RouteMetadata",
    "B14RoutingOptions",
    "B14MultimodalChatRequest",
    "MAX_B14_IMAGE_BYTES",
    "MAX_B14_MULTIMODAL_PARTS",
    "B14PostJSONTransport",
    "B14Transport",
    "B14TransportResponse",
    "B14_STREAM_PREVIEW_PATH",
    "B14StreamEvent",
    "B14StreamingClient",
    "DEFAULT_GROUNDING_PREAMBLE",
    "MAX_GROUNDED_EVIDENCE_CONTEXT_CHARS",
    "MAX_GROUNDED_SOURCES",
    "MAX_RESEARCH_PAGE_FETCHES",
    "MAX_RESEARCH_QUERIES",
    "MAX_RESEARCH_SOURCES",
    "GroundedResearchResult",
    "GroundedResearchRuntime",
    "GroundedSynthesisResult",
    "GroundingPolicy",
    "GroundingRuntimeError",
    "PreparedGrounding",
    "ResearchProgress",
    "dedupe_evidence",
    "parse_research_queries",
    "prepare_combined_grounding_context",
    "prepare_grounding_context",
    "MAX_ADDITIONAL_SYSTEM_CONTEXT_CHARS",
    "MAX_COMPOSED_SYSTEM_CHARS",
    "MAX_EXECUTION_MESSAGE_CHARS",
    "MAX_EXECUTION_MESSAGES",
    "B14Executor",
    "ExecutionRequest",
    "ExecutionResult",
    "ExecutionRuntime",
    "ExecutionRuntimeError",
    "ExecutionContext",
    "IdempotencyAdapter",
    "IdempotencyConflictError",
    "request_fingerprint",
    "ContextualExecutionRunner",
    "PreparedExecution",
    "prepare_execution",
    "RetrievalProvider",
    "RetrievalRequest",
    "RetrievedItem",
    "RetrievalPolicy",
    "PreparedRetrieval",
    "RetrievalContractError",
    "prepare_retrieval_context",
    "MAX_RETRIEVAL_NAMESPACES",
    "MAX_RETRIEVAL_RESULTS",
    "MemoryContractError",
    "MemoryNamespace",
    "MemoryProvenance",
    "MemoryScope",
    "MemoryWriteAuthorization",
    "MemoryWriteOrigin",
    "MemoryWritePolicy",
    "MemoryWriteRequest",
    "PreparedMemoryWrite",
    "authorize_memory_write",
    "MAX_MEMORY_APPROVED_PROPOSALS",
    "MAX_MEMORY_AUTH_NAMESPACES",
    "MAX_MEMORY_CONTENT_CHARS",
    "MAX_MEMORY_DERIVED_FROM",
    "MAX_MEMORY_SOURCE_REF_CHARS",
    "MemoryReadAuthorization",
    "MemoryReadPolicy",
    "authorize_memory_retrieval",
    "MemoryWriteDisposition",
    "MemoryWriteReceipt",
    "IdempotentMemoryWriteAdapter",
    "persist_authorized_memory_write",
    "validate_memory_write_receipt",
    "RetrievalScore",
    "RankedMemoryItem",
    "rank_retrieval_results",
    "assemble_long_context",
    "B14StreamExecutor",
    "StreamingExecutionEvent",
    "StreamingExecutionRuntime",
    "AgentApprovalError",
    "AgentContinuationState",
    "ApprovalOutcome",
    "ApprovalPause",
    "ApprovalRequirement",
    "ContinuationStatus",
    "VerifiedApprovalDecision",
    "approval_pause_from_tool_error",
    "resolve_approval_pause",
    "assert_same_invocation",
    "tool_invocation_digest",
    "MAX_APPROVAL_CHECKPOINTS",
    "MAX_CAPABILITIES",
    "MAX_CONNECTOR_IDS",
    "MAX_DESCRIPTION_CHARS",
    "MAX_INSTRUCTION_CHARS",
    "MAX_SKILL_IDS",
    "MAX_TOOL_IDS",
    "AgentApprovalCheckpoint",
    "AgentDefinitionError",
    "AgentExecutionBudget",
    "AgentTerminalReason",
    "BoundedAgentDefinition",
    "missing_agent_capabilities",
    "AgentProfileCompilationError",
    "CompiledAgentProfile",
    "ToolRuntimeBinding",
    "TrustedAgentRuntimePolicy",
    "compile_agent_profile",
    "MAX_AGENT_PLAN_DEPENDENCIES",
    "MAX_AGENT_PLAN_INPUT_CHARS",
    "MAX_AGENT_PLAN_OBJECTIVE_CHARS",
    "MAX_AGENT_PLAN_STEPS",
    "AgentPlan",
    "AgentPlanStep",
    "AgentPlanner",
    "AgentPlannerError",
    "validate_agent_plan",
    "validate_agent_plan_input",
    "AgentFailure",
    "AgentFailureSource",
    "AgentRecoveryAction",
    "AgentRecoveryContext",
    "AgentRecoveryDecision",
    "AgentRecoveryError",
    "AgentRecoveryPolicy",
    "decide_agent_recovery",
    "AgentDelegationError",
    "AgentDelegationRequest",
    "DelegatedAgentAuthority",
    "authorize_agent_delegation",
    "delegation_fingerprint",
    "AgentEvent",
    "AgentEventError",
    "AgentEventKind",
    "public_agent_event",
    "ApprovalHook",
    "MAX_ALLOWED_TOOLS",
    "MAX_APPROVAL_HOOKS",
    "MAX_CONNECTOR_REQUIREMENTS",
    "MAX_REQUIRED_CAPABILITIES",
    "ReusableSkillPackage",
    "SkillPackageError",
    "missing_required_capabilities",
    "SkillCompatibility",
    "SkillCompatibilityDecision",
    "SkillMigrationMap",
    "SkillVersionError",
    "evaluate_skill_compatibility",
    "parse_skill_major",
    "SkillInstallation",
    "SkillInstallationSnapshot",
    "SkillInstallStatus",
    "SkillRegistryError",
    "SkillRegistrySnapshot",
    "resolve_enabled_skill",
    "ActivatedSkillProfile",
    "compile_enabled_skill",
    "CompiledSkillProfile",
    "SkillRuntimeAdapterError",
    "TrustedSkillRuntimePolicy",
    "compile_skill_profile",
    "MAX_REGISTERED_TOOLS",
    "ToolRegistryError",
    "ToolRegistrySnapshot",
    "ConnectorDescriptor",
    "ConnectorRegistryError",
    "ConnectorRegistrySnapshot",
    "MAX_CONNECTOR_TOOLS",
    "MAX_REGISTERED_CONNECTORS",
    "EffectiveToolResources",
    "ToolResourcePolicy",
    "ToolResourcePolicyError",
    "resolve_tool_resources",
    "ConnectorLifecycleEvent",
    "ConnectorLifecycleKind",
    "ToolLifecycleError",
    "ToolLifecycleEvent",
    "ToolLifecycleKind",
    "ClaimDerivation",
    "ClaimEvidenceLink",
    "ClaimEvidenceRelation",
    "EvidenceClaim",
    "EvidenceGraph",
    "EvidenceGraphError",
    "evidence_graph",
    "AcceptedVerification",
    "EvidenceValidator",
    "EvidenceVerificationError",
    "MAX_ALLOWED_VALIDATORS",
    "MAX_VERIFICATION_EVIDENCE_IDS",
    "MAX_VERIFICATION_SUMMARY_CHARS",
    "TrustedVerificationPolicy",
    "VerificationDisposition",
    "VerificationRequest",
    "VerificationVerdict",
    "accept_verification_verdict",
    "EvidenceCitationError",
    "GroundedCitation",
    "GroundedCitationBundle",
    "MAX_CITATIONS_PER_CLAIM",
    "project_grounded_citations",
    "ClaimAssessment",
    "ClaimAssessmentState",
    "EvidenceAssessmentError",
    "MAX_ASSESSMENT_EVIDENCE_IDS",
    "assess_claim",
    "is_verification_satisfied",
    "OrchestrationEvent",
    "OrchestrationEventError",
    "OrchestrationEventKind",
    "public_orchestration_event",
    "OrchestrationError",
    "OrchestrationRequest",
    "OrchestrationResult",
    "OrchestrationRunner",
    "MAX_TOOL_ARGUMENT_BYTES",
    "MAX_TOOL_OUTPUT_BYTES",
    "ToolAuthorizationContext",
    "ToolExecutionResult",
    "ToolHandler",
    "ToolInvocation",
    "ToolRuntime",
    "ToolRuntimeError",
]
