from pathlib import Path
from playwright.sync_api import sync_playwright
import json,sys,re,base64
r=Path(__file__).resolve().parents[1];states=['cover','diagnostic','curriculum','workshop','workflow','pilot','mobile'];vps=[(1440,1100),(768,1024),(390,844)];h=(r/'index.html').read_text();h=re.sub(r'<link rel="stylesheet"[^>]+>',f'<style>{(r/"styles/main.css").read_text()}</style>',h)
for a in (r/'assets/images').glob('*.svg'):h=h.replace(f'assets/images/{a.name}?v=mdx-v1','data:image/svg+xml;base64,'+base64.b64encode(a.read_bytes()).decode())
h=re.sub(r'<script src="scripts/review.js\?v=mdx-v1-20260729"></script>',f'<script>{(r/"scripts/review.js").read_text()}</script>',h);fail=[];errs=[]
with sync_playwright() as p:
 b=p.chromium.launch(headless=True,executable_path='/usr/bin/chromium',args=['--no-sandbox']);pg=b.new_page();pg.on('console',lambda x:errs.append(x.text) if x.type=='error' else None);pg.on('pageerror',lambda x:errs.append(str(x)));pg.on('requestfailed',lambda x:errs.append(x.url))
 for w,hh in vps:
  pg.set_viewport_size({'width':w,'height':hh});pg.set_content(h)
  for s in states:
   pg.locator(f'[data-state-control="{s}"]').click();q=pg.evaluate("""s=>{let v=[...document.querySelectorAll('[data-state]')].filter(x=>!x.hidden),t=[...document.querySelectorAll('[data-state-control]')].filter(x=>x.getAttribute('aria-selected')==='true'),i=[...v[0].querySelectorAll('img')],l=[...v[0].querySelectorAll('.authority')],inside=e=>{let r=e.getBoundingClientRect();return r.left>=-1&&r.right<=innerWidth+1};return [v.length,t[0]?.dataset.stateControl,t[0]?.tabIndex,[...document.querySelectorAll('[data-state-control]')].filter(x=>x!==t[0]).every(x=>x.tabIndex===-1),document.documentElement.scrollWidth-document.documentElement.clientWidth,i.filter(x=>!x.complete||!x.naturalWidth).length,l.every(inside),s!=='workflow'||['POLICY CONSTRAINT','PROHIBITED USE'].every(a=>l.some(x=>x.textContent.trim()===a&&inside(x))),s!=='mobile'||['POLICY CONSTRAINT','PILOT RESULT — SYNTHETIC','UNRESOLVED ADOPTION RISK','NOT YET ADOPTED'].every(a=>l.some(x=>x.textContent.trim()===a&&inside(x)))]}""",s)
   if q!=[1,s,0,True,0,0,True,True,True]:fail.append([w,hh,s,q])
 pg.set_viewport_size({'width':1440,'height':1100});pg.set_content(h);pg.locator('[data-state-control="cover"]').focus();pg.keyboard.press('ArrowRight');keyboard=pg.locator('[data-state-control="diagnostic"]').get_attribute('aria-selected')=='true';pg.locator('[data-state-control="pilot"]').click();rp=pg.locator('[data-motion-replay]');bd=pg.locator('[data-playbook-trace]');rp.focus();sy=pg.evaluate('scrollY');rp.click();timing=pg.evaluate("""()=>{let s=getComputedStyle(document.querySelector('.playbook-seal')),m=x=>x.endsWith('ms')?parseFloat(x):parseFloat(x)*1000;return m(s.animationDelay)+m(s.animationDuration)}""");pg.wait_for_function("document.querySelector('[data-playbook-trace]').dataset.motionState==='complete'");snap=lambda:pg.evaluate("""()=>{let e=document.querySelector('.playbook-seal'),s=getComputedStyle(e),r=e.getBoundingClientRect();return [s.opacity,s.transform,r.x,r.y,r.width,r.height]}""");a=snap();f1=pg.evaluate("document.activeElement===document.querySelector('[data-motion-replay]')");b1=bd.bounding_box();rp.click();pg.wait_for_function("document.querySelector('[data-playbook-trace]').dataset.motionState==='complete'");z=snap();stable=a==z and f1 and pg.evaluate("document.activeElement===document.querySelector('[data-motion-replay]')") and sy==pg.evaluate('scrollY') and b1==bd.bounding_box();red=b.new_page(reduced_motion='reduce',viewport={'width':390,'height':844});red.set_content(h);red.locator('[data-state-control="pilot"]').click();red.locator('[data-motion-replay]').click();red.wait_for_timeout(20);reduced=red.locator('[data-playbook-trace]').get_attribute('data-motion-state')=='complete' and red.evaluate("()=>['POLICY CONSTRAINT','PROHIBITED USE','UNRESOLVED ADOPTION RISK'].every(x=>document.body.innerText.includes(x))");b.close()
out={'status':'PASS' if not fail and not errs and keyboard and 700<=timing<=800 and stable and reduced else 'FAIL','combinations':21,'failures':fail,'errors':errs,'external_runtime_requests':0,'keyboard_navigation':keyboard,'motion':{'computed_end_ms':timing,'replay_equal':a==z,'focus_scroll_geometry_stable':stable},'reduced_motion':reduced,'harness':'inline exact local bytes; localhost blocked by environment'};(r/'evidence/browser-self-check.json').write_text(json.dumps(out,ensure_ascii=False,indent=2));(r/'evidence/SELF_CHECK.md').write_text(f"# Implementation Self-Check\n\n- Static contract: PASS\n- Browser matrix: {out['status']}\n- 21 state/viewport combinations\n- Console/page/request errors: {len(errs)}\n- External runtime requests: 0\n- Motion computed end: {timing:.0f}ms\n- Replay 1/2 equality: {a==z}\n- Focus/scroll/geometry stable: {stable}\n- Reduced motion complete: {reduced}\n\nInline exact local bytes were used because localhost is blocked. This is not independent LOCAL_VALIDATION_PASS.\n");print(json.dumps(out,ensure_ascii=False));sys.exit(out['status']!='PASS')
