"""#2962: hwpx.create Skill facade contract tests.

The facade must compose accepted authorities and add none: bounded structured
content goes through the canonical Core serializer, and the generated bytes
are only reported as success after the common intake gate, the existing
validate authority, the existing read authority and an exact text round trip
all agreed.
"""

from __future__ import annotations

import socket
import unittest
from unittest import mock

from padiem_ai_core.document_normalization import MAX_DOCUMENT_NAME_CHARS
from padiem_ai_core.document_semantics import DocumentNormalizationError
from padiem_ai_core.hwpx_package_serializer import (
    MAX_HWPX_PACKAGE_TEXT_CHARS,
    MAX_HWPX_PARAGRAPH_CHARS,
    MAX_HWPX_PARAGRAPHS,
    MAX_HWPX_SECTIONS,
    HwpxPackageContent,
    HwpxPackageSection,
)

from kagent import hwpx_skill
from kagent.claw_skill_registry import (
    CAPABILITY_HWPX_CREATE,
    CAPABILITY_HWPX_READ,
    CAPABILITY_HWPX_VALIDATE,
    RESERVED_CAPABILITY_IDS,
)
from kagent.document_parser_contract import is_bounded_reason_code
from kagent.file_intake_safety import DetectedFormat, IntakeDecision, inspect_file
from kagent.hwpx_skill import (
    DEFAULT_CREATE_FILENAME,
    HWPX_MEDIA_TYPE,
    HWPX_SUFFIX,
    MAX_CREATE_FILENAME_CHARS,
    REASON_CREATE_GATE_REJECTED,
    REASON_CREATE_READBACK_REJECTED,
    REASON_CREATE_ROUNDTRIP_MISMATCH,
    REASON_CREATE_SERIALIZER_REJECTED,
    REASON_CREATE_VALIDATE_REJECTED,
    STATUS_OK,
    STATUS_REFUSED,
    VALIDATION_SCOPE_GATE_AND_TEXT,
    VALIDATION_STATUS_GATE_REFUSED,
    VALIDATION_STATUS_NOT_RUN,
    VALIDATION_STATUS_READBACK_REFUSED,
    VALIDATION_STATUS_ROUNDTRIP_MISMATCH,
    VALIDATION_STATUS_ROUNDTRIP_OK,
    VALIDATION_STATUS_VALIDATE_REFUSED,
    hwpx_create,
    hwpx_read,
    hwpx_validate,
)

RECEIPT_KEYS = frozenset(
    {
        "status",
        "capability_id",
        "reason_code",
        "note",
        "media_type",
        "suggested_filename",
        "byte_size",
        "section_count",
        "paragraph_count",
        "validation_status",
    }
)

KOREAN_TEXT = "견적서\n합계 1,000원"


def _content(*sections: tuple[str, ...]) -> HwpxPackageContent:
    return HwpxPackageContent(
        sections=tuple(HwpxPackageSection(paragraphs=tuple(paragraphs)) for paragraphs in sections)
    )


def _png_bytes() -> bytes:
    return b"\x89PNG\r\n\x1a\n" + b"\x00" * 16


def _gate_metadata() -> hwpx_skill.HwpxGateMetadata:
    """Real gate metadata from a payload the gate refuses, for receipt tests."""

    return hwpx_skill.HwpxGateMetadata.from_gate(inspect_file("fake.hwpx", _png_bytes()))


def _refused_validate_receipt() -> hwpx_skill.HwpxValidateReceipt:
    return hwpx_skill.HwpxValidateReceipt(
        status=STATUS_REFUSED,
        capability_id=CAPABILITY_HWPX_VALIDATE,
        reason_code="hwpx_mimetype_mismatch",
        note=None,
        scope=VALIDATION_SCOPE_GATE_AND_TEXT,
        full_spec_support_claimed=False,
        text_present=False,
        gate=_gate_metadata(),
    )


def _ok_validate_receipt() -> hwpx_skill.HwpxValidateReceipt:
    return hwpx_skill.HwpxValidateReceipt(
        status=STATUS_OK,
        capability_id=CAPABILITY_HWPX_VALIDATE,
        reason_code="ok",
        note=None,
        scope=VALIDATION_SCOPE_GATE_AND_TEXT,
        full_spec_support_claimed=False,
        text_present=True,
        gate=_gate_metadata(),
    )


def _refused_read_receipt() -> hwpx_skill.HwpxReadReceipt:
    return hwpx_skill.HwpxReadReceipt(
        status=STATUS_REFUSED,
        capability_id=CAPABILITY_HWPX_READ,
        reason_code="hwpx_mimetype_mismatch",
        note=None,
        text=None,
    )


def _mismatched_read_receipt() -> hwpx_skill.HwpxReadReceipt:
    return hwpx_skill.HwpxReadReceipt(
        status=STATUS_OK,
        capability_id=CAPABILITY_HWPX_READ,
        reason_code="ok",
        note=None,
        text="다른 텍스트",
    )


class HwpxCreateSuccessTests(unittest.TestCase):
    def test_simple_korean_create_succeeds(self) -> None:
        result = hwpx_create(_content(("견적서",)))
        receipt = result.receipt
        self.assertEqual(receipt.status, STATUS_OK)
        self.assertEqual(receipt.reason_code, "ok")
        self.assertEqual(receipt.capability_id, CAPABILITY_HWPX_CREATE)
        self.assertIsNone(receipt.note)
        self.assertEqual(receipt.validation_status, VALIDATION_STATUS_ROUNDTRIP_OK)
        self.assertEqual(receipt.section_count, 1)
        self.assertEqual(receipt.paragraph_count, 1)
        self.assertGreater(receipt.byte_size, 0)
        self.assertIsNotNone(result.artifact)

    def test_multi_section_create_reports_section_count(self) -> None:
        result = hwpx_create(_content(("발주서", "품목 A 수량 2"), ("검수", "합격"), ("서명",)))
        self.assertEqual(result.receipt.status, STATUS_OK)
        self.assertEqual(result.receipt.section_count, 3)
        self.assertEqual(result.receipt.paragraph_count, 5)

    def test_multi_paragraph_create_reports_paragraph_count(self) -> None:
        result = hwpx_create(_content(("하나", "둘", "셋", "넷")))
        self.assertEqual(result.receipt.status, STATUS_OK)
        self.assertEqual(result.receipt.section_count, 1)
        self.assertEqual(result.receipt.paragraph_count, 4)

    def test_korean_text_round_trip_is_exact(self) -> None:
        result = hwpx_create(_content(("견적서", "합계 1,000원")))
        read = hwpx_read(result.receipt.suggested_filename, result.artifact.payload)
        self.assertEqual(read.status, STATUS_OK)
        self.assertEqual(read.text, KOREAN_TEXT)

    def test_multisection_round_trip_order_is_exact(self) -> None:
        result = hwpx_create(_content(("발주서", "품목 A 수량 2"), ("검수", "합격")))
        read = hwpx_read(result.receipt.suggested_filename, result.artifact.payload)
        self.assertEqual(read.text, "발주서\n품목 A 수량 2\n검수\n합격")

    def test_xml_metacharacter_text_round_trips_safely(self) -> None:
        expected = '<PADIEM> & "quoted" \'apostrophe\''
        result = hwpx_create(_content((expected,)))
        self.assertEqual(result.receipt.status, STATUS_OK)
        read = hwpx_read(result.receipt.suggested_filename, result.artifact.payload)
        self.assertEqual(read.text, expected)
        self.assertNotIn("&lt;", read.text)
        self.assertNotIn("&amp;", read.text)

    def test_same_input_creates_identical_bytes(self) -> None:
        first = hwpx_create(_content(("결정적", "출력")))
        second = hwpx_create(_content(("결정적", "출력")))
        self.assertEqual(first.artifact.payload, second.artifact.payload)
        self.assertEqual(first.receipt.byte_size, second.receipt.byte_size)

    def test_empty_section_is_dropped_without_losing_text(self) -> None:
        result = hwpx_create(_content((), ("본문",)))
        self.assertEqual(result.receipt.status, STATUS_OK)
        self.assertEqual(result.receipt.section_count, 2)
        self.assertEqual(result.receipt.paragraph_count, 1)
        read = hwpx_read(result.receipt.suggested_filename, result.artifact.payload)
        self.assertEqual(read.text, "본문")

    def test_empty_paragraphs_do_not_shift_the_projection(self) -> None:
        result = hwpx_create(_content(("가", "", "나")))
        self.assertEqual(result.receipt.status, STATUS_OK)
        self.assertEqual(result.receipt.paragraph_count, 3)
        read = hwpx_read(result.receipt.suggested_filename, result.artifact.payload)
        self.assertEqual(read.text, "가\n나")

    def test_surrounding_whitespace_is_projected_not_rejected(self) -> None:
        result = hwpx_create(_content(("  여백  ",)))
        self.assertEqual(result.receipt.status, STATUS_OK)
        read = hwpx_read(result.receipt.suggested_filename, result.artifact.payload)
        self.assertEqual(read.text, "여백")

    def test_media_type_is_hwpx(self) -> None:
        result = hwpx_create(_content(("미디어",)))
        self.assertEqual(result.receipt.media_type, HWPX_MEDIA_TYPE)
        self.assertEqual(result.receipt.media_type, "application/hwp+zip")
        self.assertEqual(result.artifact.media_type, HWPX_MEDIA_TYPE)

    def test_default_suggested_filename_is_fixed_and_canonical(self) -> None:
        result = hwpx_create(_content(("이름",)))
        self.assertEqual(result.receipt.suggested_filename, DEFAULT_CREATE_FILENAME)
        self.assertTrue(result.receipt.suggested_filename.endswith(HWPX_SUFFIX))


class GeneratedPayloadAuthorityTests(unittest.TestCase):
    def test_generated_payload_passes_the_common_intake_gate(self) -> None:
        result = hwpx_create(_content(("게이트", "통과")))
        gate = inspect_file(result.receipt.suggested_filename, result.artifact.payload)
        self.assertEqual(gate.decision, IntakeDecision.SAFE_CANDIDATE)
        self.assertTrue(gate.safe_to_parse)
        self.assertFalse(gate.encrypted)
        self.assertEqual(gate.archive_depth_reached, 0)

    def test_generated_payload_is_a_truthful_hwpx_candidate(self) -> None:
        result = hwpx_create(_content(("후보",)))
        gate = inspect_file(result.receipt.suggested_filename, result.artifact.payload)
        self.assertEqual(gate.detected_format, DetectedFormat.HWPX_CANDIDATE)
        self.assertEqual(gate.detected_media_type, HWPX_MEDIA_TYPE)
        self.assertFalse(gate.mismatch)

    def test_existing_validate_accepts_the_generated_payload(self) -> None:
        result = hwpx_create(_content(("검증",)))
        receipt = hwpx_validate(result.receipt.suggested_filename, result.artifact.payload)
        self.assertEqual(receipt.status, STATUS_OK)
        self.assertEqual(receipt.capability_id, CAPABILITY_HWPX_VALIDATE)
        self.assertTrue(receipt.text_present)
        self.assertFalse(receipt.full_spec_support_claimed)

    def test_existing_read_returns_the_requested_text(self) -> None:
        result = hwpx_create(_content(("읽기", "왕복")))
        receipt = hwpx_read(result.receipt.suggested_filename, result.artifact.payload)
        self.assertEqual(receipt.status, STATUS_OK)
        self.assertEqual(receipt.capability_id, CAPABILITY_HWPX_READ)
        self.assertEqual(receipt.text, "읽기\n왕복")

    def test_artifact_holds_bounded_in_memory_bytes(self) -> None:
        result = hwpx_create(_content(("바이트",)))
        artifact = result.artifact
        self.assertIsInstance(artifact.payload, bytes)
        self.assertTrue(artifact.payload.startswith(b"PK"))
        self.assertEqual(artifact.byte_size, len(artifact.payload))
        self.assertEqual(result.receipt.byte_size, len(artifact.payload))

    def test_create_uses_only_the_canonical_serializer(self) -> None:
        with mock.patch(
            "kagent.hwpx_skill.serialize_hwpx_package",
            wraps=hwpx_skill.serialize_hwpx_package,
        ) as serializer:
            result = hwpx_create(_content(("단일 권위",)))
        self.assertEqual(result.receipt.status, STATUS_OK)
        serializer.assert_called_once()
        (content,), _ = serializer.call_args
        self.assertIsInstance(content, HwpxPackageContent)


class PublicProjectionTests(unittest.TestCase):
    def test_public_receipt_is_exactly_the_bounded_key_set(self) -> None:
        public = hwpx_create(_content(("공개",))).to_public_dict()
        self.assertEqual(set(public), set(RECEIPT_KEYS))
        for key in public:
            lowered = str(key).lower()
            self.assertNotIn("payload", lowered)
            self.assertNotIn("bytes_", lowered)
            self.assertNotIn("xml", lowered)
            self.assertNotIn("member", lowered)
            self.assertNotIn("path", lowered)
            self.assertNotIn("content", lowered)

    def test_public_receipt_excludes_the_payload(self) -> None:
        result = hwpx_create(_content(("비공개",)))
        public = result.to_public_dict()
        self.assertNotIn("payload", public)
        self.assertNotIn("artifact", public)
        self.assertNotIn(result.artifact.payload, public.values())
        self.assertNotIn(str(result.artifact.payload), str(public))
        self.assertNotIn(b"PK\x03\x04", str(public).encode("utf-8"))

    def test_public_receipt_excludes_xml_and_archive_member_names(self) -> None:
        result = hwpx_create(_content(("구조",)))
        rendered = str(result.to_public_dict())
        for leak in (
            "<?xml",
            "<hs:sec",
            "<hp:p>",
            "hp:t",
            "hancom.co.kr",
            "Contents/section",
            "section1.xml",
            "mimetype",
            "ZIP_STORED",
        ):
            self.assertNotIn(leak, rendered, leak)

    def test_public_receipt_excludes_host_paths(self) -> None:
        result = hwpx_create(_content(("경로",)), filename=r"C:\temp\secret\doc.hwpx")
        rendered = str(result.to_public_dict())
        self.assertNotIn("secret", rendered)
        self.assertNotIn("temp", rendered)
        self.assertNotIn("C:", rendered)
        self.assertNotIn("\\", rendered)

    def test_refused_receipt_carries_no_artifact_metadata(self) -> None:
        result = hwpx_create(_content(("",)))
        receipt = result.receipt
        self.assertEqual(receipt.status, STATUS_REFUSED)
        self.assertIsNone(result.artifact)
        self.assertIsNone(receipt.media_type)
        self.assertIsNone(receipt.suggested_filename)
        self.assertIsNone(receipt.byte_size)
        self.assertIsNone(receipt.section_count)
        self.assertIsNone(receipt.paragraph_count)
        self.assertEqual(set(result.to_public_dict()), set(RECEIPT_KEYS))


class SuggestedFilenameTests(unittest.TestCase):
    def test_posix_traversal_name_is_sanitized_flat(self) -> None:
        result = hwpx_create(_content(("이름",)), filename="../../etc/passwd")
        self.assertEqual(result.receipt.status, STATUS_OK)
        self.assertEqual(result.receipt.suggested_filename, f"passwd{HWPX_SUFFIX}")
        self.assertNotIn("/", result.receipt.suggested_filename)

    def test_windows_path_name_is_sanitized_flat(self) -> None:
        result = hwpx_create(_content(("이름",)), filename=r"C:\temp\..\evil.hwpx")
        self.assertEqual(result.receipt.suggested_filename, f"evil{HWPX_SUFFIX}")
        self.assertNotIn("\\", result.receipt.suggested_filename)
        self.assertNotIn(":", result.receipt.suggested_filename)

    def test_control_characters_and_dot_only_names_fall_back_to_default(self) -> None:
        for name in ("..", ".", "\x00\x01", "   ", "", "unnamed"):
            with self.subTest(name=name):
                result = hwpx_create(_content(("이름",)), filename=name)
                self.assertEqual(result.receipt.status, STATUS_OK)
                self.assertEqual(result.receipt.suggested_filename, DEFAULT_CREATE_FILENAME)

    def test_foreign_extension_is_replaced_by_the_canonical_suffix(self) -> None:
        for name in ("report.txt", "report", "report.docx", "report.hwpx"):
            with self.subTest(name=name):
                result = hwpx_create(_content(("이름",)), filename=name)
                self.assertEqual(result.receipt.suggested_filename, f"report{HWPX_SUFFIX}")

    def test_long_name_stays_within_the_core_name_bound(self) -> None:
        result = hwpx_create(_content(("이름",)), filename="가" * 400)
        name = result.receipt.suggested_filename
        self.assertEqual(result.receipt.status, STATUS_OK)
        self.assertTrue(name.endswith(HWPX_SUFFIX))
        self.assertLessEqual(len(name), MAX_CREATE_FILENAME_CHARS)
        self.assertLessEqual(len(name.encode("utf-8")), MAX_CREATE_FILENAME_CHARS)
        # The local bound is a mirror: it must never drift above the Core bound
        # the isolated parser envelope enforces.
        self.assertLessEqual(MAX_CREATE_FILENAME_CHARS, MAX_DOCUMENT_NAME_CHARS)


class CreateFailClosedTests(unittest.TestCase):
    def test_empty_content_fails_closed(self) -> None:
        result = hwpx_create(HwpxPackageContent(sections=()))
        self.assertEqual(result.receipt.status, STATUS_REFUSED)
        self.assertEqual(result.receipt.reason_code, REASON_CREATE_SERIALIZER_REJECTED)
        self.assertEqual(result.receipt.note, "hwpx_serialize_model")
        self.assertEqual(result.receipt.validation_status, VALIDATION_STATUS_NOT_RUN)
        self.assertIsNone(result.artifact)

    def test_malformed_model_fails_closed(self) -> None:
        malformed = (
            None,
            "not a model",
            HwpxPackageContent(sections=["section"]),
            HwpxPackageContent(sections=("not a section",)),
            HwpxPackageContent(sections=(HwpxPackageSection(paragraphs=["list"]),)),
            HwpxPackageContent(sections=(HwpxPackageSection(paragraphs=()),)),
        )
        for content in malformed:
            with self.subTest(content=repr(content)):
                result = hwpx_create(content)
                self.assertEqual(result.receipt.status, STATUS_REFUSED)
                self.assertEqual(result.receipt.reason_code, REASON_CREATE_SERIALIZER_REJECTED)
                self.assertIsNone(result.artifact)

    def test_non_string_paragraph_fails_closed(self) -> None:
        for paragraph in (1, b"bytes", None, ["nested"]):
            with self.subTest(paragraph=repr(paragraph)):
                result = hwpx_create(
                    HwpxPackageContent(
                        sections=(HwpxPackageSection(paragraphs=(paragraph,)),)
                    )
                )
                self.assertEqual(result.receipt.status, STATUS_REFUSED)
                self.assertEqual(result.receipt.reason_code, REASON_CREATE_SERIALIZER_REJECTED)
                self.assertEqual(result.receipt.note, "hwpx_serialize_model")

    def test_oversized_paragraph_fails_closed(self) -> None:
        result = hwpx_create(_content(("가" * (MAX_HWPX_PARAGRAPH_CHARS + 1),)))
        self.assertEqual(result.receipt.status, STATUS_REFUSED)
        self.assertEqual(result.receipt.reason_code, REASON_CREATE_SERIALIZER_REJECTED)
        self.assertEqual(result.receipt.note, "hwpx_serialize_paragraph_text_limit")

    def test_excessive_paragraph_count_fails_closed(self) -> None:
        result = hwpx_create(_content(tuple("문단" for _ in range(MAX_HWPX_PARAGRAPHS + 1))))
        self.assertEqual(result.receipt.status, STATUS_REFUSED)
        self.assertEqual(result.receipt.reason_code, REASON_CREATE_SERIALIZER_REJECTED)
        self.assertEqual(result.receipt.note, "hwpx_serialize_paragraph_limit")

    def test_excessive_section_count_fails_closed(self) -> None:
        result = hwpx_create(_content(*tuple(("본문",) for _ in range(MAX_HWPX_SECTIONS + 1))))
        self.assertEqual(result.receipt.status, STATUS_REFUSED)
        self.assertEqual(result.receipt.reason_code, REASON_CREATE_SERIALIZER_REJECTED)
        self.assertEqual(result.receipt.note, "hwpx_serialize_section_limit")

    def test_total_text_bound_is_enforced(self) -> None:
        per_paragraph = MAX_HWPX_PARAGRAPH_CHARS
        paragraphs = (MAX_HWPX_PACKAGE_TEXT_CHARS // per_paragraph) + 1
        result = hwpx_create(_content(tuple("가" * per_paragraph for _ in range(paragraphs))))
        self.assertEqual(result.receipt.status, STATUS_REFUSED)
        self.assertEqual(result.receipt.reason_code, REASON_CREATE_SERIALIZER_REJECTED)
        self.assertEqual(result.receipt.note, "hwpx_serialize_text_limit")

    def test_invalid_xml_control_character_fails_closed(self) -> None:
        for text in ("제어\x00문자", "벨\x07", "수직\x0b"):
            with self.subTest(text=text):
                result = hwpx_create(_content((text,)))
                self.assertEqual(result.receipt.status, STATUS_REFUSED)
                self.assertEqual(result.receipt.reason_code, REASON_CREATE_SERIALIZER_REJECTED)
                self.assertEqual(result.receipt.note, "hwpx_serialize_control_char")

    def test_carriage_return_text_is_outside_the_supported_range(self) -> None:
        # XML line-end normalisation would turn CR into LF, so an exact round
        # trip is impossible: create refuses instead of silently rewriting.
        result = hwpx_create(_content(("줄\r바꿈",)))
        self.assertEqual(result.receipt.status, STATUS_REFUSED)
        self.assertEqual(result.receipt.reason_code, REASON_CREATE_ROUNDTRIP_MISMATCH)
        self.assertEqual(result.receipt.validation_status, VALIDATION_STATUS_ROUNDTRIP_MISMATCH)
        self.assertIsNone(result.artifact)

    def test_serializer_failure_fails_closed_without_fallback(self) -> None:
        with mock.patch(
            "kagent.hwpx_skill.serialize_hwpx_package",
            side_effect=DocumentNormalizationError("hwpx_serialize_model", "bounded refusal"),
        ), mock.patch(
            "kagent.hwpx_skill.intake_document",
            side_effect=AssertionError("no fallback document route is allowed"),
        ):
            result = hwpx_create(_content(("실패",)))
        self.assertEqual(result.receipt.status, STATUS_REFUSED)
        self.assertEqual(result.receipt.reason_code, REASON_CREATE_SERIALIZER_REJECTED)
        self.assertEqual(result.receipt.note, "hwpx_serialize_model")
        self.assertIsNone(result.artifact)

    def test_serializer_returning_no_bytes_fails_closed(self) -> None:
        for value in (b"", None, "PK\x03\x04"):
            with self.subTest(value=repr(value)):
                with mock.patch("kagent.hwpx_skill.serialize_hwpx_package", return_value=value):
                    result = hwpx_create(_content(("실패",)))
                self.assertEqual(result.receipt.status, STATUS_REFUSED)
                self.assertEqual(result.receipt.reason_code, REASON_CREATE_SERIALIZER_REJECTED)
                self.assertIsNone(result.artifact)

    def test_common_gate_failure_prevents_create_success(self) -> None:
        # Both gate refusal branches: a denied payload and an admissible
        # payload whose content is not HWPX.
        cases = (
            (inspect_file("fake.hwpx", b""), "empty_payload"),
            (inspect_file("fake.hwpx", _png_bytes()), "content_mismatch"),
        )
        for denied, expected_note in cases:
            with self.subTest(note=expected_note):
                self.assertIsNot(denied.detected_format, DetectedFormat.HWPX_CANDIDATE)
                with mock.patch("kagent.hwpx_skill.inspect_file", return_value=denied):
                    result = hwpx_create(_content(("게이트",)))
                self.assertEqual(result.receipt.status, STATUS_REFUSED)
                self.assertEqual(result.receipt.reason_code, REASON_CREATE_GATE_REJECTED)
                self.assertEqual(result.receipt.note, expected_note)
                self.assertEqual(
                    result.receipt.validation_status, VALIDATION_STATUS_GATE_REFUSED
                )
                self.assertIsNone(result.artifact)

    def test_validate_failure_prevents_create_success(self) -> None:
        with mock.patch(
            "kagent.hwpx_skill.hwpx_validate", return_value=_refused_validate_receipt()
        ):
            result = hwpx_create(_content(("검증",)))
        self.assertEqual(result.receipt.status, STATUS_REFUSED)
        self.assertEqual(result.receipt.reason_code, REASON_CREATE_VALIDATE_REJECTED)
        self.assertEqual(result.receipt.note, "hwpx_mimetype_mismatch")
        self.assertEqual(result.receipt.validation_status, VALIDATION_STATUS_VALIDATE_REFUSED)
        self.assertIsNone(result.artifact)

    def test_readback_failure_prevents_create_success(self) -> None:
        # Validate is stubbed ok so the flow reaches the readback stage: the
        # real validate authority calls the same read authority.
        with mock.patch(
            "kagent.hwpx_skill.hwpx_validate", return_value=_ok_validate_receipt()
        ), mock.patch("kagent.hwpx_skill.hwpx_read", return_value=_refused_read_receipt()):
            result = hwpx_create(_content(("읽기",)))
        self.assertEqual(result.receipt.status, STATUS_REFUSED)
        self.assertEqual(result.receipt.reason_code, REASON_CREATE_READBACK_REJECTED)
        self.assertEqual(result.receipt.note, "hwpx_mimetype_mismatch")
        self.assertEqual(result.receipt.validation_status, VALIDATION_STATUS_READBACK_REFUSED)
        self.assertIsNone(result.artifact)

    def test_roundtrip_mismatch_prevents_create_success(self) -> None:
        with mock.patch(
            "kagent.hwpx_skill.hwpx_validate", return_value=_ok_validate_receipt()
        ), mock.patch("kagent.hwpx_skill.hwpx_read", return_value=_mismatched_read_receipt()):
            result = hwpx_create(_content(("왕복",)))
        self.assertEqual(result.receipt.status, STATUS_REFUSED)
        self.assertEqual(result.receipt.reason_code, REASON_CREATE_ROUNDTRIP_MISMATCH)
        self.assertEqual(result.receipt.validation_status, VALIDATION_STATUS_ROUNDTRIP_MISMATCH)
        self.assertIsNone(result.artifact)

    def test_model_rejection_never_reaches_post_create_verification(self) -> None:
        with mock.patch(
            "kagent.hwpx_skill.hwpx_validate",
            side_effect=AssertionError("validate must not run for a refused model"),
        ) as validate, mock.patch(
            "kagent.hwpx_skill.hwpx_read",
            side_effect=AssertionError("read must not run for a refused model"),
        ) as read:
            result = hwpx_create(HwpxPackageContent(sections=()))
        self.assertEqual(result.receipt.status, STATUS_REFUSED)
        validate.assert_not_called()
        read.assert_not_called()

    def test_refusal_reason_codes_and_notes_are_bounded(self) -> None:
        refusals = (
            hwpx_create(HwpxPackageContent(sections=())),
            hwpx_create(_content(("제어\x00",))),
            hwpx_create(_content(("줄\r바꿈",))),
        )
        for result in refusals:
            with self.subTest(reason=result.receipt.reason_code):
                self.assertTrue(is_bounded_reason_code(result.receipt.reason_code))
                if result.receipt.note is not None:
                    self.assertTrue(is_bounded_reason_code(result.receipt.note))
                self.assertNotIn(" ", result.receipt.reason_code)
                self.assertNotIn("/", result.receipt.reason_code)


class CreateAuthorityContractTests(unittest.TestCase):
    def test_capability_id_is_an_existing_reserved_id(self) -> None:
        self.assertIn(CAPABILITY_HWPX_CREATE, RESERVED_CAPABILITY_IDS)
        self.assertEqual(CAPABILITY_HWPX_CREATE, "hwpx.create")
        result = hwpx_create(_content(("권위",)))
        self.assertEqual(result.receipt.capability_id, CAPABILITY_HWPX_CREATE)

    def test_acceptance_block_matches_issue_2962(self) -> None:
        expected = {
            "HWPX_CREATE_FOUNDATION": "PASS",
            "HWPX_CREATE": "FOUNDATION_ONLY",
            "CORE_HWPX_SERIALIZER_REUSED": "YES",
            "SINGLE_HWPX_SERIALIZER_AUTHORITY": "YES",
            "COMMON_FILE_INTAKE_GATE_REUSED": "YES",
            "CREATE_SUCCESS_REQUIRES_ROUNDTRIP": "YES",
            "SECOND_HWPX_SERIALIZER_AUTHORITY": "0",
            "SECOND_HWPX_PARSER_AUTHORITY": "0",
            "SECOND_ARCHIVE_GATE_AUTHORITY": "0",
            "SECOND_XML_AUTHORITY": "0",
            "SECOND_SKILL_REGISTRY_AUTHORITY": "0",
            "CALLER_RAW_XML_INPUT": "0",
            "CALLER_ZIP_MEMBER_INPUT": "0",
            "CALLER_MEMBER_NAME_INPUT": "0",
            "CALLER_HOST_PATH_AUTHORITY": "0",
            "HOST_FS_WRITE": "0",
            "HOST_FS_EXTRACTION": "0",
            "RAW_XML_PUBLIC_OUTPUT": "0",
            "PAYLOAD_PUBLIC_OUTPUT": "0",
            "ZIP_MEMBER_PUBLIC_OUTPUT": "0",
            "HOST_PATH_PUBLIC_OUTPUT": "0",
            "HWPX_FULL_SPEC_SUPPORT": "NO",
            "DOCUMENT_EXPORT_HWPX_ENABLED": "NO",
            "NETWORK_CALLS": "0",
            "PROVIDER_CALLS": "0",
            "PRODUCTION_MUTATION": "0",
        }
        for key, value in expected.items():
            self.assertEqual(hwpx_skill.ACCEPTANCE.get(key), value, key)

    def test_edit_is_foundation_only_and_insert_table_is_narrowly_scoped(self) -> None:
        self.assertEqual(hwpx_skill.ACCEPTANCE.get("HWPX_EDIT_FOUNDATION"), "PASS")
        self.assertEqual(hwpx_skill.ACCEPTANCE.get("HWPX_EDIT"), "FOUNDATION_ONLY")
        self.assertNotIn(hwpx_skill.ACCEPTANCE.get("HWPX_EDIT"), {"PASS", "YES"})
        self.assertEqual(hwpx_skill.ACCEPTANCE.get("HWPX_TEMPLATE_FILL_FOUNDATION"), "PASS")
        self.assertEqual(hwpx_skill.ACCEPTANCE.get("HWPX_TEMPLATE_FILL"), "PASS")
        self.assertEqual(hwpx_skill.ACCEPTANCE.get("HWPX_TEMPLATE_FILL_SCOPE"), "BOUNDED_FOUNDATION")
        self.assertEqual(hwpx_skill.ACCEPTANCE.get("HWPX_INSERT_TABLE_FACADE"), "PASS")
        self.assertEqual(hwpx_skill.ACCEPTANCE.get("TABLE_INSERT"), "PASS")
        self.assertEqual(
            hwpx_skill.ACCEPTANCE.get("TABLE_INSERT_SCOPE"),
            "BOUNDED_CANONICAL_BLOCK_SUBSET",
        )
        # #2825 claims bounded image insertion over the same edit capability;
        # create itself still claims none, and the wider image authorities stay
        # unclaimed.
        self.assertEqual(hwpx_skill.ACCEPTANCE.get("TABLE_EDIT"), "NOT_CLAIMED")
        self.assertEqual(hwpx_skill.ACCEPTANCE.get("IMAGE_INSERT"), "PASS")
        self.assertEqual(
            hwpx_skill.ACCEPTANCE.get("IMAGE_INSERT_SCOPE"),
            "BOUNDED_PNG_CANONICAL_MANIFEST_PACKAGE",
        )
        self.assertEqual(hwpx_skill.ACCEPTANCE.get("IMAGE_EDIT"), "NOT_CLAIMED")

    def test_facade_has_no_second_serializer_archive_or_xml_authority(self) -> None:
        source = (hwpx_skill.__file__ or "")
        with open(source, encoding="utf-8") as handle:
            text = handle.read()
        # Code-level tokens only: the module docstring names these concepts in
        # prose precisely to say they are not implemented here.
        for forbidden in (
            "import zipfile",
            "from zipfile",
            "ZipFile(",
            "writestr(",
            "BytesIO(",
            "xml.etree",
            "ElementTree(",
            "minidom",
            "escape(",
            "_section_xml",
            "_package_bytes",
            "Contents/",
        ):
            self.assertNotIn(forbidden, text, forbidden)

    def test_create_path_writes_nothing_to_the_host_filesystem(self) -> None:
        with mock.patch("builtins.open", side_effect=AssertionError("host write attempted")):
            result = hwpx_create(_content(("파일시스템",)))
        self.assertEqual(result.receipt.status, STATUS_OK)
        self.assertIsInstance(result.artifact.payload, bytes)

    def test_create_path_opens_no_network_socket(self) -> None:
        def _forbidden_socket(*args: object, **kwargs: object) -> None:
            raise AssertionError("network access attempted")

        with mock.patch.object(socket, "socket", side_effect=_forbidden_socket):
            result = hwpx_create(_content(("네트워크",)))
        self.assertEqual(result.receipt.status, STATUS_OK)

    def test_create_receipt_rejects_unbounded_reason_code(self) -> None:
        with self.assertRaises(ValueError):
            hwpx_skill.HwpxCreateReceipt(
                status=STATUS_REFUSED,
                capability_id=CAPABILITY_HWPX_CREATE,
                reason_code="leak:secret/path",
                note=None,
                media_type=None,
                suggested_filename=None,
                byte_size=None,
                section_count=None,
                paragraph_count=None,
                validation_status=VALIDATION_STATUS_NOT_RUN,
            )

    def test_create_receipt_rejects_unbounded_note(self) -> None:
        with self.assertRaises(ValueError):
            hwpx_skill.HwpxCreateReceipt(
                status=STATUS_REFUSED,
                capability_id=CAPABILITY_HWPX_CREATE,
                reason_code=REASON_CREATE_SERIALIZER_REJECTED,
                note="문서 변환 실패 — ooxml_invalid_xml",
                media_type=None,
                suggested_filename=None,
                byte_size=None,
                section_count=None,
                paragraph_count=None,
                validation_status=VALIDATION_STATUS_NOT_RUN,
            )

    def test_ok_receipt_cannot_skip_the_roundtrip_verification(self) -> None:
        with self.assertRaises(ValueError):
            hwpx_skill.HwpxCreateReceipt(
                status=STATUS_OK,
                capability_id=CAPABILITY_HWPX_CREATE,
                reason_code="ok",
                note=None,
                media_type=HWPX_MEDIA_TYPE,
                suggested_filename=DEFAULT_CREATE_FILENAME,
                byte_size=1,
                section_count=1,
                paragraph_count=1,
                validation_status=VALIDATION_STATUS_GATE_REFUSED,
            )

    def test_refused_receipt_cannot_claim_a_verified_roundtrip(self) -> None:
        with self.assertRaises(ValueError):
            hwpx_skill.HwpxCreateReceipt(
                status=STATUS_REFUSED,
                capability_id=CAPABILITY_HWPX_CREATE,
                reason_code=REASON_CREATE_GATE_REJECTED,
                note=None,
                media_type=None,
                suggested_filename=None,
                byte_size=None,
                section_count=None,
                paragraph_count=None,
                validation_status=VALIDATION_STATUS_ROUNDTRIP_OK,
            )

    def test_ok_result_requires_its_artifact(self) -> None:
        receipt = hwpx_create(_content(("산출물",))).receipt
        with self.assertRaises(ValueError):
            hwpx_skill.HwpxCreateResult(receipt=receipt, artifact=None)

    def test_refused_result_cannot_carry_an_artifact(self) -> None:
        ok_artifact = hwpx_create(_content(("산출물",))).artifact
        refused_receipt = hwpx_create(HwpxPackageContent(sections=())).receipt
        with self.assertRaises(ValueError):
            hwpx_skill.HwpxCreateResult(receipt=refused_receipt, artifact=ok_artifact)


if __name__ == "__main__":
    unittest.main()
