"""#2937/#2962: bounded native HWPX Skill facade — inspect / read / validate / create.

This module is a facade and receipt layer over authorities that already exist
and are already accepted. It introduces no ZIP walker, no XML parser, no
serializer, no host filesystem write or extraction, no network/provider call
and no new runtime dependency.

Composition order (the common gate always runs first)::

    raw HWPX bytes
    -> kagent.file_intake_safety.inspect_file()      (#2824 common gate)
    -> truthful HWPX_CANDIDATE (content, never extension-only)
    -> kagent.document_intake.intake_document()      (routing + isolated Core parse)
    -> bounded HWPX Skill receipt

``hwpx.create`` composes those same accepted authorities in the other
direction::

    bounded structured content (Core HwpxPackageContent, #2941 model)
    -> padiem_ai_core.hwpx_package_serializer.serialize_hwpx_package()
    -> in-memory HWPX bytes (never written to the host filesystem)
    -> inspect_file()      (the common gate must return HWPX_CANDIDATE)
    -> hwpx_validate()     (existing validate authority)
    -> hwpx_read()         (existing read authority)
    -> exact round-trip text equality
    -> bounded create receipt + in-memory artifact

Authority boundaries
--------------------
- ``inspect_file`` remains the single archive/path/expansion/MIME gate
  (``SECOND_ARCHIVE_GATE_AUTHORITY=0``).
- Core ``extract_hwpx_text`` (via ``intake_document``'s isolated parser
  boundary) remains the single HWPX text parser
  (``SECOND_HWPX_PARSER_AUTHORITY=0``, ``SECOND_XML_AUTHORITY=0``).
- Core ``serialize_hwpx_package`` remains the single HWPX byte producer
  (``SINGLE_HWPX_SERIALIZER_AUTHORITY=YES``,
  ``SECOND_HWPX_SERIALIZER_AUTHORITY=0``). The facade accepts only the
  structured ``HwpxPackageContent`` model: raw XML, ZIP member names, archive
  paths, namespace URIs, mimetype content, compression choice and serializer
  limits all stay outside caller authority, and no XML or ZIP assembly exists
  here.
- ``CREATE_SUCCESS_REQUIRES_ROUNDTRIP=YES``: generated bytes are reported as
  success only after the common gate admitted them as ``HWPX_CANDIDATE``, the
  existing validate and read authorities accepted them, and the readback text
  equals the requested text exactly. A refusal at any stage fails closed with
  a bounded reason code and never falls back to another format.
- The file extension is advisory; admission requires the gate's
  ``HWPX_CANDIDATE`` decision (``DIRECT_EXTENSION_AUTHORITY=NO``).
- Receipts expose bounded metadata and bounded reason vocabulary only: never
  raw ZIP member names, raw XML, payload bytes or host paths. The create
  artifact, which does carry the generated bytes for artifact handoff, stays
  outside the public projection, and no host filesystem write happens at all.

Capability mapping uses existing reserved ids — no Skill Registry edit:
``hwpx.inspect`` foundation is served under ``CAPABILITY_FILE_INSPECT``
(``file.inspect``), ``hwpx.read`` under ``CAPABILITY_HWPX_READ``,
``hwpx.validate`` under ``CAPABILITY_HWPX_VALIDATE`` and ``hwpx.create`` under
``CAPABILITY_HWPX_CREATE``.

Scope honesty (#2825 parent remains OPEN): ``hwpx.create`` is a foundation over
bounded plain section/paragraph text only. It does not implement edit,
template fill, table insertion, image insertion or legacy HWP conversion, it
does not produce style- or specification-complete HWPX, and it does not enable
document export (``HWPX_FULL_SPEC_SUPPORT=NO``,
``DOCUMENT_EXPORT_HWPX_ENABLED=NO``). Validation scope stays package gate
admission plus Core text extraction (``VALIDATION_SCOPE_GATE_AND_TEXT``);
full HWPX specification conformance is never claimed
(``full_spec_support_claimed=False`` on every validate receipt).
"""

from __future__ import annotations

from dataclasses import dataclass

from padiem_ai_core.document_semantics import DocumentNormalizationError
from padiem_ai_core.hwpx_package_serializer import (
    HwpxPackageContent,
    serialize_hwpx_package,
)

from .claw_skill_registry import (
    CAPABILITY_FILE_INSPECT,
    CAPABILITY_HWPX_CREATE,
    CAPABILITY_HWPX_READ,
    CAPABILITY_HWPX_VALIDATE,
)
from .document_intake import intake_document
from .document_parser_contract import is_bounded_reason_code
from .file_intake_safety import (
    DetectedFormat,
    FileIntakeResult,
    inspect_file,
    sanitize_filename,
)

__all__ = [
    "ACCEPTANCE",
    "DEFAULT_CREATE_FILENAME",
    "HWPX_MEDIA_TYPE",
    "HWPX_SUFFIX",
    "MAX_CREATE_FILENAME_CHARS",
    "REASON_CONTENT_MISMATCH",
    "REASON_CREATE_GATE_REJECTED",
    "REASON_CREATE_READBACK_REJECTED",
    "REASON_CREATE_ROUNDTRIP_MISMATCH",
    "REASON_CREATE_SERIALIZER_REJECTED",
    "REASON_CREATE_VALIDATE_REJECTED",
    "REASON_HWpx_ROUTE_REQUIRED",
    "REASON_INTAKE_REJECTED",
    "STATUS_OK",
    "STATUS_REFUSED",
    "VALIDATION_SCOPE_GATE_AND_TEXT",
    "VALIDATION_STATUS_GATE_REFUSED",
    "VALIDATION_STATUS_NOT_RUN",
    "VALIDATION_STATUS_READBACK_REFUSED",
    "VALIDATION_STATUS_ROUNDTRIP_MISMATCH",
    "VALIDATION_STATUS_ROUNDTRIP_OK",
    "VALIDATION_STATUS_VALIDATE_REFUSED",
    "HwpxCreateArtifact",
    "HwpxCreateReceipt",
    "HwpxCreateResult",
    "HwpxGateMetadata",
    "HwpxInspectReceipt",
    "HwpxReadReceipt",
    "HwpxValidateReceipt",
    "hwpx_create",
    "hwpx_inspect",
    "hwpx_read",
    "hwpx_validate",
]

HWPX_MEDIA_TYPE = "application/hwp+zip"
HWPX_SUFFIX = ".hwpx"

STATUS_OK = "ok"
STATUS_REFUSED = "refused"

REASON_CONTENT_MISMATCH = "content_mismatch"
REASON_HWpx_ROUTE_REQUIRED = "hwpx_route_required"
REASON_INTAKE_REJECTED = "intake_rejected"

#: Bounded ``hwpx.create`` refusal vocabulary. Each code names the stage that
#: refused; the underlying bounded code of that stage travels in the receipt
#: ``note``, never as free text.
REASON_CREATE_SERIALIZER_REJECTED = "create_serializer_rejected"
REASON_CREATE_GATE_REJECTED = "create_gate_rejected"
REASON_CREATE_VALIDATE_REJECTED = "create_validate_rejected"
REASON_CREATE_READBACK_REJECTED = "create_readback_rejected"
REASON_CREATE_ROUNDTRIP_MISMATCH = "create_roundtrip_mismatch"

#: Post-create verification outcome. ``roundtrip_ok`` is the only value that
#: may accompany a successful create: the common gate admitted the generated
#: package, the existing validate and read authorities accepted it, and the
#: readback text matched the requested text exactly.
VALIDATION_STATUS_ROUNDTRIP_OK = "roundtrip_ok"
VALIDATION_STATUS_NOT_RUN = "not_run"
VALIDATION_STATUS_GATE_REFUSED = "gate_refused"
VALIDATION_STATUS_VALIDATE_REFUSED = "validate_refused"
VALIDATION_STATUS_READBACK_REFUSED = "readback_refused"
VALIDATION_STATUS_ROUNDTRIP_MISMATCH = "roundtrip_mismatch"

_CREATE_VALIDATION_STATUSES = frozenset(
    {
        VALIDATION_STATUS_ROUNDTRIP_OK,
        VALIDATION_STATUS_NOT_RUN,
        VALIDATION_STATUS_GATE_REFUSED,
        VALIDATION_STATUS_VALIDATE_REFUSED,
        VALIDATION_STATUS_READBACK_REFUSED,
        VALIDATION_STATUS_ROUNDTRIP_MISMATCH,
    }
)

#: Presentation metadata only, and the fallback whenever a caller-supplied
#: name projects onto nothing safe. Nothing here is a package authority.
DEFAULT_CREATE_STEM = "padiem-document"
DEFAULT_CREATE_FILENAME = f"{DEFAULT_CREATE_STEM}{HWPX_SUFFIX}"

#: The sanitizer's sentinel for a name that projected onto no safe character.
_SANITIZED_EMPTY_NAME = "unnamed"

#: Mirrors the Core document-name bound the isolated parser envelope enforces
#: (``padiem_ai_core.document_normalization.MAX_DOCUMENT_NAME_CHARS``). A
#: longer name would be a programmer error at that envelope, so the facade
#: projects every suggested name below this bound. ``test_hwpx_skill_create``
#: asserts this stays at or below the Core value instead of trusting a copy.
MAX_CREATE_FILENAME_CHARS = 120

#: The only validation claim this foundation makes: the common gate admitted
#: the package and the existing Core parser produced (or refused) text.
VALIDATION_SCOPE_GATE_AND_TEXT = "gate_admission_and_text_extraction"

ACCEPTANCE: dict[str, str] = {
    "HWPX_INSPECT_FOUNDATION": "PASS",
    "HWPX_READ_FOUNDATION": "PASS",
    "HWPX_VALIDATE_FOUNDATION": "PASS",
    "HWPX_CREATE_FOUNDATION": "PASS",
    "COMMON_FILE_INTAKE_GATE_REUSED": "YES",
    "DIRECT_EXTENSION_AUTHORITY": "NO",
    "SINGLE_HWPX_SERIALIZER_AUTHORITY": "YES",
    "CORE_HWPX_SERIALIZER_REUSED": "YES",
    "CREATE_SUCCESS_REQUIRES_ROUNDTRIP": "YES",
    "SECOND_HWPX_PARSER_AUTHORITY": "0",
    "SECOND_HWPX_SERIALIZER_AUTHORITY": "0",
    "SECOND_ARCHIVE_GATE_AUTHORITY": "0",
    "SECOND_XML_AUTHORITY": "0",
    "SECOND_SKILL_REGISTRY_AUTHORITY": "0",
    "CALLER_RAW_XML_INPUT": "0",
    "CALLER_ZIP_MEMBER_INPUT": "0",
    "CALLER_MEMBER_NAME_INPUT": "0",
    "CALLER_HOST_PATH_AUTHORITY": "0",
    "HOST_FS_EXTRACTION": "0",
    "HOST_FS_WRITE": "0",
    "RAW_XML_PUBLIC_OUTPUT": "0",
    "PAYLOAD_PUBLIC_OUTPUT": "0",
    "ZIP_MEMBER_PUBLIC_OUTPUT": "0",
    "HOST_PATH_PUBLIC_OUTPUT": "0",
    "UNSUPPORTED_FEATURES_EXPLICIT": "YES",
    "NEW_RUNTIME_DEPENDENCY": "0",
    "NETWORK_CALLS": "0",
    "PROVIDER_CALLS": "0",
    "EXTERNAL_SEND": "0",
    "PRODUCTION_MUTATION": "0",
    # Create exists as a bounded plain-text foundation only: full create,
    # specification completeness and document export stay unclaimed.
    "HWPX_CREATE": "FOUNDATION_ONLY",
    "HWPX_FULL_SPEC_SUPPORT": "NO",
    "DOCUMENT_EXPORT_HWPX_ENABLED": "NO",
    "HWPX_EDIT": "NOT_CLAIMED",
    "HWPX_TEMPLATE_FILL": "NOT_CLAIMED",
    "TABLE_INSERT": "NOT_CLAIMED",
    "IMAGE_INSERT": "NOT_CLAIMED",
}


def _require_receipt_fields(status: str, reason_code: str) -> None:
    if status not in (STATUS_OK, STATUS_REFUSED):
        raise ValueError("hwpx_skill: receipt status must be ok or refused")
    if not is_bounded_reason_code(reason_code):
        raise ValueError("hwpx_skill: receipt reason_code must be a bounded identifier")
    if status == STATUS_OK and reason_code != "ok":
        raise ValueError("hwpx_skill: an ok receipt must carry reason_code ok")
    if status == STATUS_REFUSED and reason_code == "ok":
        raise ValueError("hwpx_skill: a refused receipt must not claim reason ok")


@dataclass(frozen=True, slots=True)
class HwpxGateMetadata:
    """Bounded projection of the common gate result.

    Mirrors ``FileIntakeResult.safe_dict`` minus the filename: media type,
    byte size, archive counts, depth, mismatch/encrypted/safety state only.
    Never contains entry names, entry contents, raw bytes or any path.
    """

    decision: str
    reason_code: str
    detected_format: str
    detected_media_type: str
    extension_media_type: str | None
    mismatch: bool
    encrypted: bool
    byte_size: int
    archive_entry_count: int
    archive_uncompressed_bytes: int
    archive_depth: int
    safe_to_parse: bool
    hwpx_candidate: bool

    def __post_init__(self) -> None:
        if not is_bounded_reason_code(self.reason_code):
            raise ValueError("hwpx_skill: gate reason_code must be a bounded identifier")

    @classmethod
    def from_gate(cls, gate: FileIntakeResult) -> HwpxGateMetadata:
        return cls(
            decision=gate.decision.value,
            reason_code=gate.reason_code,
            detected_format=gate.detected_format.value,
            detected_media_type=gate.detected_media_type,
            extension_media_type=gate.extension_media_type,
            mismatch=gate.mismatch,
            encrypted=gate.encrypted,
            byte_size=gate.raw_bytes,
            archive_entry_count=gate.archive_entry_count,
            archive_uncompressed_bytes=gate.archive_uncompressed_bytes,
            archive_depth=gate.archive_depth_reached,
            safe_to_parse=gate.safe_to_parse,
            hwpx_candidate=gate.detected_format is DetectedFormat.HWPX_CANDIDATE,
        )

    def to_public_dict(self) -> dict[str, object]:
        return {
            "decision": self.decision,
            "reason_code": self.reason_code,
            "detected_format": self.detected_format,
            "detected_media_type": self.detected_media_type,
            "extension_media_type": self.extension_media_type,
            "mismatch": self.mismatch,
            "encrypted": self.encrypted,
            "byte_size": self.byte_size,
            "archive_entry_count": self.archive_entry_count,
            "archive_uncompressed_bytes": self.archive_uncompressed_bytes,
            "archive_depth": self.archive_depth,
            "safe_to_parse": self.safe_to_parse,
            "hwpx_candidate": self.hwpx_candidate,
        }


@dataclass(frozen=True, slots=True)
class HwpxInspectReceipt:
    """Bounded hwpx.inspect result over the common gate only (no parser run)."""

    status: str
    capability_id: str
    reason_code: str
    gate: HwpxGateMetadata

    def __post_init__(self) -> None:
        _require_receipt_fields(self.status, self.reason_code)

    def to_public_dict(self) -> dict[str, object]:
        return {
            "status": self.status,
            "capability_id": self.capability_id,
            "reason_code": self.reason_code,
            "gate": self.gate.to_public_dict(),
        }


@dataclass(frozen=True, slots=True)
class HwpxReadReceipt:
    """Bounded hwpx.read result: extracted text on success, note/reason only on refusal."""

    status: str
    capability_id: str
    reason_code: str
    note: str | None
    text: str | None

    def __post_init__(self) -> None:
        _require_receipt_fields(self.status, self.reason_code)
        if self.status == STATUS_OK and self.text is None:
            raise ValueError("hwpx_skill: an ok read receipt must carry text")
        if self.status == STATUS_REFUSED and self.text is not None:
            raise ValueError("hwpx_skill: a refused read receipt must not carry text")

    def to_public_dict(self) -> dict[str, object]:
        return {
            "status": self.status,
            "capability_id": self.capability_id,
            "reason_code": self.reason_code,
            "note": self.note,
            "text": self.text,
        }


@dataclass(frozen=True, slots=True)
class HwpxValidateReceipt:
    """Bounded hwpx.validate result: gate metadata + parse outcome, scope-explicit.

    ``full_spec_support_claimed`` is always False: this foundation validates
    package admission and text extraction only, and never silently claims that
    every HWPX construct is supported.
    """

    status: str
    capability_id: str
    reason_code: str
    note: str | None
    scope: str
    full_spec_support_claimed: bool
    text_present: bool
    gate: HwpxGateMetadata

    def __post_init__(self) -> None:
        _require_receipt_fields(self.status, self.reason_code)
        if self.scope != VALIDATION_SCOPE_GATE_AND_TEXT:
            raise ValueError("hwpx_skill: scope must stay at gate admission and text extraction")
        if self.full_spec_support_claimed:
            raise ValueError("hwpx_skill: full HWPX spec support is never claimed")
        if self.status == STATUS_OK and not self.text_present:
            raise ValueError("hwpx_skill: an ok validate receipt must report text_present")

    def to_public_dict(self) -> dict[str, object]:
        return {
            "status": self.status,
            "capability_id": self.capability_id,
            "reason_code": self.reason_code,
            "note": self.note,
            "scope": self.scope,
            "full_spec_support_claimed": self.full_spec_support_claimed,
            "text_present": self.text_present,
            "gate": self.gate.to_public_dict(),
        }


def _gate_refusal(gate: FileIntakeResult) -> str | None:
    """Bounded stage-one refusal code, or None once HWPX_CANDIDATE is confirmed."""

    if not gate.safe_to_parse:
        return gate.reason_code
    if gate.detected_format is not DetectedFormat.HWPX_CANDIDATE:
        return REASON_CONTENT_MISMATCH
    return None


def hwpx_inspect(filename: str, payload: bytes) -> HwpxInspectReceipt:
    """Bounded HWPX inspection over the common gate. Runs no parser.

    Admits only a truthful ``HWPX_CANDIDATE``: content decides, the
    extension stays advisory. Refusals carry the gate's bounded reason code
    or ``content_mismatch`` with the detected format in the gate metadata.
    """

    gate = inspect_file(filename, payload)
    metadata = HwpxGateMetadata.from_gate(gate)
    refusal = _gate_refusal(gate)
    if refusal is None:
        return HwpxInspectReceipt(
            status=STATUS_OK,
            capability_id=CAPABILITY_FILE_INSPECT,
            reason_code="ok",
            gate=metadata,
        )
    return HwpxInspectReceipt(
        status=STATUS_REFUSED,
        capability_id=CAPABILITY_FILE_INSPECT,
        reason_code=refusal,
        gate=metadata,
    )


def hwpx_read(filename: str, payload: bytes) -> HwpxReadReceipt:
    """Bounded HWPX text extraction.

    Runs the common gate first, requires ``HWPX_CANDIDATE``, then reuses
    ``intake_document`` (which re-runs the same gate before its isolated Core
    parse). Refusals surface a bounded reason code plus, when the refusal came
    from the existing intake/parser layer, that layer's existing bounded note.
    """

    gate = inspect_file(filename, payload)
    refusal = _gate_refusal(gate)
    if refusal is not None:
        return HwpxReadReceipt(
            status=STATUS_REFUSED,
            capability_id=CAPABILITY_HWPX_READ,
            reason_code=refusal,
            note=None,
            text=None,
        )

    intake = intake_document(filename, payload)
    if intake is None:
        return HwpxReadReceipt(
            status=STATUS_REFUSED,
            capability_id=CAPABILITY_HWPX_READ,
            reason_code=REASON_HWpx_ROUTE_REQUIRED,
            note=None,
            text=None,
        )
    if intake.text is not None:
        return HwpxReadReceipt(
            status=STATUS_OK,
            capability_id=CAPABILITY_HWPX_READ,
            reason_code="ok",
            note=None,
            text=intake.text,
        )
    return HwpxReadReceipt(
        status=STATUS_REFUSED,
        capability_id=CAPABILITY_HWPX_READ,
        reason_code=REASON_INTAKE_REJECTED,
        note=intake.note,
        text=None,
    )


def hwpx_validate(filename: str, payload: bytes) -> HwpxValidateReceipt:
    """Bounded HWPX validation receipt: gate result composed with parser result.

    Malformed, encrypted, unsafe-path, archive-bomb, mimetype-mismatch and
    missing section/package cases remain refusals at the gate stage. An
    admitted package that the Core parser rejects (corrupt section XML, no
    extractable text) is refused with the existing bounded intake note.
    Scope stays ``gate_admission_and_text_extraction``; full specification
    conformance is never claimed.
    """

    gate = inspect_file(filename, payload)
    metadata = HwpxGateMetadata.from_gate(gate)
    refusal = _gate_refusal(gate)
    if refusal is not None:
        return HwpxValidateReceipt(
            status=STATUS_REFUSED,
            capability_id=CAPABILITY_HWPX_VALIDATE,
            reason_code=refusal,
            note=None,
            scope=VALIDATION_SCOPE_GATE_AND_TEXT,
            full_spec_support_claimed=False,
            text_present=False,
            gate=metadata,
        )

    read = hwpx_read(filename, payload)
    if read.status == STATUS_OK:
        return HwpxValidateReceipt(
            status=STATUS_OK,
            capability_id=CAPABILITY_HWPX_VALIDATE,
            reason_code="ok",
            note=None,
            scope=VALIDATION_SCOPE_GATE_AND_TEXT,
            full_spec_support_claimed=False,
            text_present=read.text is not None and read.text != "",
            gate=metadata,
        )
    return HwpxValidateReceipt(
        status=STATUS_REFUSED,
        capability_id=CAPABILITY_HWPX_VALIDATE,
        reason_code=read.reason_code,
        note=read.note,
        scope=VALIDATION_SCOPE_GATE_AND_TEXT,
        full_spec_support_claimed=False,
        text_present=False,
        gate=metadata,
    )


# --------------------------------------------------------------------------
# hwpx.create (#2962): bounded structured content through the Core serializer
# --------------------------------------------------------------------------


@dataclass(frozen=True, slots=True)
class HwpxCreateReceipt:
    """Bounded ``hwpx.create`` projection.

    On success it reports presentation metadata plus the post-create
    verification outcome; on refusal every artifact-derived field is ``None``,
    so a refused create can never be read as a handoff. It carries bounded
    metadata and bounded reason vocabulary only — never payload bytes, raw
    XML, ZIP member names or host paths. The generated bytes live in
    :class:`HwpxCreateArtifact`, which stays outside the public projection.
    """

    status: str
    capability_id: str
    reason_code: str
    note: str | None
    media_type: str | None
    suggested_filename: str | None
    byte_size: int | None
    section_count: int | None
    paragraph_count: int | None
    validation_status: str

    def __post_init__(self) -> None:
        _require_receipt_fields(self.status, self.reason_code)
        if self.validation_status not in _CREATE_VALIDATION_STATUSES:
            raise ValueError("hwpx_skill: create validation_status must be bounded")
        if self.note is not None and not is_bounded_reason_code(self.note):
            raise ValueError("hwpx_skill: a create note must be a bounded identifier")

        if self.status == STATUS_OK:
            if self.validation_status != VALIDATION_STATUS_ROUNDTRIP_OK:
                raise ValueError("hwpx_skill: an ok create must have verified its round trip")
            if self.note is not None:
                raise ValueError("hwpx_skill: an ok create receipt carries no note")
            if self.media_type != HWPX_MEDIA_TYPE:
                raise ValueError("hwpx_skill: an ok create must report the HWPX media type")
            if not isinstance(self.suggested_filename, str) or not (
                self.suggested_filename.endswith(HWPX_SUFFIX)
            ):
                raise ValueError("hwpx_skill: an ok create name must end with the canonical suffix")
            if not isinstance(self.byte_size, int) or self.byte_size <= 0:
                raise ValueError("hwpx_skill: an ok create must report a positive byte size")
            if not isinstance(self.section_count, int) or self.section_count <= 0:
                raise ValueError("hwpx_skill: an ok create must report its section count")
            if not isinstance(self.paragraph_count, int) or self.paragraph_count <= 0:
                raise ValueError("hwpx_skill: an ok create must report its paragraph count")
            return

        if self.validation_status == VALIDATION_STATUS_ROUNDTRIP_OK:
            raise ValueError("hwpx_skill: a refused create must not claim a verified round trip")
        if any(
            value is not None
            for value in (
                self.media_type,
                self.suggested_filename,
                self.byte_size,
                self.section_count,
                self.paragraph_count,
            )
        ):
            raise ValueError("hwpx_skill: a refused create receipt carries no artifact metadata")

    def to_public_dict(self) -> dict[str, object]:
        return {
            "status": self.status,
            "capability_id": self.capability_id,
            "reason_code": self.reason_code,
            "note": self.note,
            "media_type": self.media_type,
            "suggested_filename": self.suggested_filename,
            "byte_size": self.byte_size,
            "section_count": self.section_count,
            "paragraph_count": self.paragraph_count,
            "validation_status": self.validation_status,
        }


@dataclass(frozen=True, slots=True)
class HwpxCreateArtifact:
    """In-memory create artifact for artifact handoff.

    This is the only place a created package's bytes exist. It is deliberately
    separate from :class:`HwpxCreateReceipt` so no public projection can carry
    the payload, and nothing here is written to the host filesystem.
    """

    payload: bytes
    media_type: str
    suggested_filename: str
    byte_size: int
    section_count: int
    paragraph_count: int

    def __post_init__(self) -> None:
        if not isinstance(self.payload, bytes) or not self.payload:
            raise ValueError("hwpx_skill: a create artifact requires bounded bytes")
        if self.media_type != HWPX_MEDIA_TYPE:
            raise ValueError("hwpx_skill: a create artifact must be the HWPX media type")
        if not isinstance(self.suggested_filename, str) or not (
            self.suggested_filename.endswith(HWPX_SUFFIX)
        ):
            raise ValueError("hwpx_skill: a create artifact name must use the canonical suffix")
        if self.byte_size != len(self.payload):
            raise ValueError("hwpx_skill: a create artifact byte size must match its payload")
        if self.section_count <= 0 or self.paragraph_count <= 0:
            raise ValueError("hwpx_skill: a create artifact must report its bounded counts")


@dataclass(frozen=True, slots=True)
class HwpxCreateResult:
    """One create outcome: the public receipt plus, on success only, the bytes.

    ``to_public_dict`` delegates to the receipt, so the public projection of a
    create is exactly the bounded receipt and can never include the payload.
    A successful receipt always carries its artifact and a refused receipt
    never does, which keeps "no artifact" and "no success" the same fact.
    """

    receipt: HwpxCreateReceipt
    artifact: HwpxCreateArtifact | None = None

    def __post_init__(self) -> None:
        if self.receipt.status == STATUS_OK and self.artifact is None:
            raise ValueError("hwpx_skill: an ok create result must carry its artifact")
        if self.receipt.status != STATUS_OK and self.artifact is not None:
            raise ValueError("hwpx_skill: a refused create result must not carry an artifact")

    def to_public_dict(self) -> dict[str, object]:
        return self.receipt.to_public_dict()


def _bounded_note(value: object) -> str | None:
    """A bounded identifier or ``None``; free text never reaches a receipt."""

    return value if is_bounded_reason_code(value) else None


def _expected_readback_text(content: HwpxPackageContent) -> str:
    """The exact text the existing Core reader must return for this content.

    Mirrors the accepted Core HWPX projection: within a section, non-empty
    paragraph values joined by a newline and stripped; empty sections dropped;
    sections joined by a newline and stripped. It is only consulted after the
    canonical serializer accepted the model, so the structure is bounded.
    """

    sections: list[str] = []
    for section in content.sections:
        section_text = "\n".join(text for text in section.paragraphs if text).strip()
        if section_text:
            sections.append(section_text)
    return "\n".join(sections).strip()


def _suggested_filename(filename: str | None) -> str:
    """Project a caller-supplied name onto a flat, bounded ``.hwpx`` name.

    Presentation metadata only. The canonical sanitizer removes separators,
    traversal and control material, a trailing extension is replaced by the
    canonical ``.hwpx`` suffix, and a name that projects onto nothing safe
    falls back to the fixed default. Nothing is written to the host.
    """

    if not isinstance(filename, str) or not filename.strip():
        return DEFAULT_CREATE_FILENAME
    safe = sanitize_filename(filename, max_bytes=MAX_CREATE_FILENAME_CHARS - len(HWPX_SUFFIX))
    stem = safe.rsplit(".", 1)[0] if "." in safe else safe
    stem = stem.strip(" .")
    if not stem or stem == _SANITIZED_EMPTY_NAME:
        return DEFAULT_CREATE_FILENAME
    return f"{stem}{HWPX_SUFFIX}"


def _create_refusal(
    reason_code: str,
    *,
    note: str | None,
    validation_status: str,
) -> HwpxCreateResult:
    return HwpxCreateResult(
        receipt=HwpxCreateReceipt(
            status=STATUS_REFUSED,
            capability_id=CAPABILITY_HWPX_CREATE,
            reason_code=reason_code,
            note=note,
            media_type=None,
            suggested_filename=None,
            byte_size=None,
            section_count=None,
            paragraph_count=None,
            validation_status=validation_status,
        ),
        artifact=None,
    )


def hwpx_create(
    content: HwpxPackageContent,
    *,
    filename: str | None = None,
) -> HwpxCreateResult:
    """Create bounded HWPX bytes from structured content, verified end to end.

    The only accepted input is the Core ``HwpxPackageContent`` model (sections
    of plain paragraph strings) and the only byte producer is the canonical
    Core serializer, so a caller never reaches raw XML, ZIP member names,
    archive paths, namespaces, mimetype content or serializer limits. Success
    is reported only after the generated bytes passed the common intake gate
    as ``HWPX_CANDIDATE``, the existing validate and read authorities accepted
    them, and the readback text matched the requested text exactly. Every
    other outcome is a bounded refusal with no artifact and no fallback
    format.

    ``filename`` is optional presentation metadata and never a package or host
    authority: it is sanitized onto a flat bounded name ending in ``.hwpx``,
    and an unusable name falls back to the fixed default.
    """

    try:
        payload = serialize_hwpx_package(content)
    except DocumentNormalizationError as error:
        return _create_refusal(
            REASON_CREATE_SERIALIZER_REJECTED,
            note=_bounded_note(getattr(error, "code", None)),
            validation_status=VALIDATION_STATUS_NOT_RUN,
        )
    if not isinstance(payload, bytes) or not payload:
        # Defence in depth: a serializer that returns no bounded byte string
        # can never produce a create success.
        return _create_refusal(
            REASON_CREATE_SERIALIZER_REJECTED,
            note=None,
            validation_status=VALIDATION_STATUS_NOT_RUN,
        )

    expected_text = _expected_readback_text(content)
    name = _suggested_filename(filename)

    gate = inspect_file(name, payload)
    refusal = _gate_refusal(gate)
    if refusal is not None:
        return _create_refusal(
            REASON_CREATE_GATE_REJECTED,
            note=_bounded_note(refusal),
            validation_status=VALIDATION_STATUS_GATE_REFUSED,
        )

    validation = hwpx_validate(name, payload)
    if validation.status != STATUS_OK:
        return _create_refusal(
            REASON_CREATE_VALIDATE_REJECTED,
            note=_bounded_note(validation.reason_code),
            validation_status=VALIDATION_STATUS_VALIDATE_REFUSED,
        )

    read = hwpx_read(name, payload)
    if read.status != STATUS_OK:
        return _create_refusal(
            REASON_CREATE_READBACK_REJECTED,
            note=_bounded_note(read.reason_code),
            validation_status=VALIDATION_STATUS_READBACK_REFUSED,
        )
    if read.text != expected_text:
        return _create_refusal(
            REASON_CREATE_ROUNDTRIP_MISMATCH,
            note=None,
            validation_status=VALIDATION_STATUS_ROUNDTRIP_MISMATCH,
        )

    section_count = len(content.sections)
    paragraph_count = sum(len(section.paragraphs) for section in content.sections)
    artifact = HwpxCreateArtifact(
        payload=payload,
        media_type=HWPX_MEDIA_TYPE,
        suggested_filename=name,
        byte_size=len(payload),
        section_count=section_count,
        paragraph_count=paragraph_count,
    )
    return HwpxCreateResult(
        receipt=HwpxCreateReceipt(
            status=STATUS_OK,
            capability_id=CAPABILITY_HWPX_CREATE,
            reason_code="ok",
            note=None,
            media_type=HWPX_MEDIA_TYPE,
            suggested_filename=name,
            byte_size=len(payload),
            section_count=section_count,
            paragraph_count=paragraph_count,
            validation_status=VALIDATION_STATUS_ROUNDTRIP_OK,
        ),
        artifact=artifact,
    )
