/*
 * AI Revenue Lab — Business Authority Registry (data only)
 *
 * Contains the 55 normalized Business records. Uses the factory
 * and vocabulary from business-authority-vocabulary.js (must be
 * loaded first).
 *
 * Each record is classified as one of:
 *   canonical, proposed-number, candidate, existing-project,
 *   reserved, number-reconciliation-required
 *
 * Last verified against origin/main SHA: b24e2452928d8181f5f3f5ee7b5d2aee66ab1538
 * Last updated: 2026-07-29
 * See docs/BUSINESS_AUTHORITY_AUDIT_2026-07-29.md for full audit.
 */

(function () {
  "use strict";
  var V = window.ARL_VOCABULARY;
  if (!V) throw new Error("business-authority-vocabulary.js must be loaded first");
  var NA = V.NUMBER_AUTHORITY;
  var UI = V.UI_STATUS;
  var UX = V.UX_STATUS;
  var BE = V.BACKEND_STATUS;
  var rec = V.rec;

  window.ARL_BUSINESSES = [
    // ═══════════════════════════════════════════════════════════
    // 1–4: CANONICAL — verified in BUSINESS_REGISTRY.md
    // ═══════════════════════════════════════════════════════════
    rec({ n: 1, s: "personal-edition", t: "Personal Edition", k: "퍼스널 에디션",
      a: NA.CANONICAL, l: "private_preview", st: "review",
      ui: UI.IN_PROGRESS, ux: UX.BLOCKED_BY_UI, be: BE.FROZEN,
      pdi: 108, ci: 108, pr: 111,
      w: "apps/personal-edition/", sty: "Cloudflare Pages branch preview",
      su: "https://feat-personal-edition-final.ai-revenue-personal-edition.pages.dev",
      d: "Preview deployed; CTO changes required", rs: "preview_draft",
      gl: "Draft PR #111", gu: "https://github.com/skerishKang/ai-revenue-lab/pull/111",
      iu: "https://github.com/skerishKang/ai-revenue-lab/issues/108",
      ca: "Fix visual and clickable-flow blockers", na: "Re-review PR #111 after fixes",
      kl: "PR #111 remains Draft; CTO review pending",
      src: "BUSINESS_REGISTRY.md; Issue #108; PR #111", lv: "2026-07-24", p: 100 }),

    rec({ n: 2, s: "living-travel", t: "Living Travel", k: "리빙 트래블",
      a: NA.CANONICAL, l: "private_preview", st: "running",
      ui: UI.APPROVED, ux: UX.NOT_STARTED, be: BE.IMPLEMENTED,
      pdi: 43, ci: 107, pr: 88,
      w: "apps/living-travel/", sty: "External staging",
      su: "https://ops-living-travel-external-s.ai-revenue-living-travel.pages.dev",
      d: "Cloudflare Pages + Modal + Neon", rs: "staging",
      gl: "Merged PR #88", gu: "https://github.com/skerishKang/ai-revenue-lab/pull/88",
      iu: "https://github.com/skerishKang/ai-revenue-lab/issues/107",
      ca: "Issue #107 Phase 3B live-provider activation",
      na: "Prepare resettable traveler/operator demo sequence",
      kl: "Remote PR/commit for Phase 3B not yet published",
      src: "Issues #32, #43, #69, #74, #86, #107; PR #88", lv: "2026-07-24", p: 35 }),

    rec({ n: 3, s: "living-fiction", t: "Living Fiction", k: "리빙 픽션",
      a: NA.CANONICAL, l: "private_preview", st: "review",
      ui: UI.APPROVED, ux: UX.NOT_STARTED, be: BE.IMPLEMENTED,
      pdi: 55, ci: 75, pr: 85,
      w: "apps/living-fiction/", sty: "Modal production workflow (404 as of 2026-07-26)",
      su: null, d: "Modal + Neon — deployment unreachable", rs: "degraded",
      gl: "Merged PR #85", gu: "https://github.com/skerishKang/ai-revenue-lab/pull/85",
      iu: "https://github.com/skerishKang/ai-revenue-lab/issues/75",
      ca: "Verify deployment and restore access",
      na: "Document synthetic invite credentials and demo-data reset procedure",
      kl: "Existing Modal URL returns 404 — deployment re-verification required",
      src: "Issues #34, #55, #75, #77; PR #85", lv: "2026-07-26", p: 32 }),

    rec({ n: 4, s: "living-learning", t: "Living Learning", k: "리빙 러닝",
      a: NA.CANONICAL, l: "private_preview", st: "running",
      ui: UI.APPROVED, ux: UX.NOT_STARTED, be: BE.NOT_APPLICABLE,
      pdi: 37, ci: 37, pr: 94,
      w: "apps/living-learning/", sty: "Cloudflare Pages static demo",
      su: "https://ai-revenue-living-learning.pages.dev/", d: "Static preview available",
      rs: "static_preview",
      gl: "Merged PR #94", gu: "https://github.com/skerishKang/ai-revenue-lab/pull/94",
      iu: "https://github.com/skerishKang/ai-revenue-lab/issues/37",
      ca: "Standardize adaptive-lesson demo narration",
      na: "Standardize first-lesson to adapted-lesson demo flow",
      kl: "Static demo only; no adaptive runtime",
      src: "Issue #37; PR #94", lv: "2026-07-24", p: 30 }),

    // ═══════════════════════════════════════════════════════════
    // 5: PROPOSED-NUMBER — Issue #99 open, registry update pending
    // ═══════════════════════════════════════════════════════════
    rec({ n: 5, s: "neighbor-market", t: "Neighbor Market", k: "우리단지 이웃가게",
      a: NA.PROPOSED, l: "concept", st: "review",
      ui: UI.IN_PROGRESS, ux: UX.BLOCKED_BY_UI, be: BE.FROZEN,
      pdi: 99, ci: 99, pr: 109,
      w: "reference/business-05-neighbor-market-v2/", sty: "Static demo in Draft PR",
      su: null, d: "Assignment pending; no production deployment", rs: "not_released",
      gl: "Draft PR #109", gu: "https://github.com/skerishKang/ai-revenue-lab/pull/109",
      iu: "https://github.com/skerishKang/ai-revenue-lab/issues/99",
      ca: "Pending canonical Business 5 assignment",
      na: "Accept canonical B05 assignment and complete static-demo review",
      kl: "Issue #99 remains OPEN; BUSINESS_REGISTRY.md still shows reserved-05",
      src: "Issue #99; Draft PR #109; reference/business-05-neighbor-market-v2/",
      lv: "2026-07-24", p: 95 }),

    // ═══════════════════════════════════════════════════════════
    // 6: NUMBER-RECONCILIATION-REQUIRED — conflicting sources
    // ═══════════════════════════════════════════════════════════
    rec({ n: 6, s: "world-feed", t: "World Feed", k: "월드 피드",
      a: NA.RECONCILIATION, l: "research", st: "planning",
      ui: UI.IN_PROGRESS, ux: UX.BLOCKED_BY_UI, be: BE.FROZEN,
      pdi: 98, ci: 98, pr: null,
      w: "apps/world-feed/", sty: "Research workspace", su: null,
      d: "Not assigned as canonical Business 6", rs: "not_released",
      gl: "Issue #98", gu: "https://github.com/skerishKang/ai-revenue-lab/issues/98",
      iu: "https://github.com/skerishKang/ai-revenue-lab/issues/98",
      ca: "Resolve numbering conflict",
      na: "Approve, reject, or revise proposed B06 mapping",
      kl: "BUSINESS_REGISTRY.md reserves 06; candidate backlog proposes world-feed as B06",
      src: "BUSINESS_REGISTRY.md (reserved-06); BUSINESS_CANDIDATE_BACKLOG.md (proposed); Issue #98",
      lv: "2026-07-24", p: 88 }),

    // ═══════════════════════════════════════════════════════════
    // 7–12: PROPOSED-NUMBER — PR #185 merged but registry doc conflict
    // ═══════════════════════════════════════════════════════════
    rec({ n: 7, s: "personal-meaning-map", t: "Personal Meaning Map", k: "개인 의미 지도",
      a: NA.PROPOSED, l: "visual_reference", st: "review",
      ui: UI.IN_PROGRESS, ux: UX.BLOCKED_BY_UI, be: BE.FROZEN,
      pdi: 166, ci: 166, pr: 174,
      w: "reference/business-07-personal-meaning-map-v1/",
      sty: "Visual reference in Draft PR", su: null, d: "Not deployed", rs: "not_released",
      gl: "Draft PR #174", gu: "https://github.com/skerishKang/ai-revenue-lab/pull/174",
      iu: "https://github.com/skerishKang/ai-revenue-lab/issues/166",
      ca: "Complete Phase 1 UI review", na: "Obtain exact-head CTO approval",
      kl: "PR #185 merged 7–12 as canonical, but BUSINESS_REGISTRY.md remains reserved",
      src: "PR #185; Issue #166; Draft PR #174", lv: "2026-07-26", p: 65 }),

    rec({ n: 8, s: "family-newspaper", t: "Family Newspaper", k: "우리 가족 신문",
      a: NA.PROPOSED, l: "visual_reference", st: "review",
      ui: UI.IN_PROGRESS, ux: UX.BLOCKED_BY_UI, be: BE.FROZEN,
      pdi: 168, ci: 168, pr: 176,
      w: "reference/business-08-family-newspaper-v1/",
      sty: "Visual reference in Draft PR", su: null, d: "Not deployed", rs: "not_released",
      gl: "Draft PR #176", gu: "https://github.com/skerishKang/ai-revenue-lab/pull/176",
      iu: "https://github.com/skerishKang/ai-revenue-lab/issues/168",
      ca: "Complete Phase 1 UI review", na: "Obtain exact-head CTO approval",
      kl: "PR #185 merged as canonical; registry doc conflict",
      src: "PR #185; Issue #168; Draft PR #176", lv: "2026-07-26", p: 60 }),

    rec({ n: 9, s: "personalized-childrens-story", t: "Personalized Children\u2019s Story", k: "우리 아이 이야기",
      a: NA.PROPOSED, l: "visual_reference", st: "review",
      ui: UI.APPROVED, ux: UX.NOT_STARTED, be: BE.FROZEN,
      pdi: 170, ci: 170, pr: 175,
      w: "reference/business-09-personalized-childrens-story-v1/",
      sty: "Approved visual reference in Draft PR", su: null, d: "Not deployed",
      rs: "not_released",
      gl: "UI_APPROVED \u00b7 Draft PR #175",
      gu: "https://github.com/skerishKang/ai-revenue-lab/pull/175",
      iu: "https://github.com/skerishKang/ai-revenue-lab/issues/170",
      ca: "Keep PR #175 Draft pending separate Ready/merge authorization",
      na: "Open Phase 2 UX only through a separately authorized issue",
      kl: "UI_APPROVED does not imply merge or UX approval",
      src: "PR #185; Issue #170; Draft PR #175 (UI_APPROVED)", lv: "2026-07-26", p: 58 }),

    rec({ n: 10, s: "fan-magazine", t: "Fan Magazine", k: "나만의 팬 매거진",
      a: NA.PROPOSED, l: "visual_reference", st: "review",
      ui: UI.IN_PROGRESS, ux: UX.BLOCKED_BY_UI, be: BE.FROZEN,
      pdi: 171, ci: 171, pr: 177,
      w: "reference/business-10-fan-magazine-v1/",
      sty: "Visual reference in Draft PR", su: null, d: "Not deployed", rs: "not_released",
      gl: "Draft PR #177", gu: "https://github.com/skerishKang/ai-revenue-lab/pull/177",
      iu: "https://github.com/skerishKang/ai-revenue-lab/issues/171",
      ca: "Complete Phase 1 UI review", na: "Obtain exact-head CTO approval",
      kl: "PR #185 merged as canonical; registry doc conflict",
      src: "PR #185; Issue #171; Draft PR #177", lv: "2026-07-26", p: 56 }),

    rec({ n: 11, s: "language-learning-magazine", t: "Language Learning Magazine", k: "나의 언어학습 매거진",
      a: NA.PROPOSED, l: "visual_reference", st: "review",
      ui: UI.IN_PROGRESS, ux: UX.BLOCKED_BY_UI, be: BE.FROZEN,
      pdi: 172, ci: 172, pr: 179,
      w: "reference/business-11-language-learning-magazine-v1/",
      sty: "Visual reference in Draft PR", su: null, d: "Not deployed", rs: "not_released",
      gl: "Draft PR #179", gu: "https://github.com/skerishKang/ai-revenue-lab/pull/179",
      iu: "https://github.com/skerishKang/ai-revenue-lab/issues/172",
      ca: "Complete Phase 1 UI review", na: "Obtain exact-head CTO approval",
      kl: "PR #185 merged as canonical; registry doc conflict",
      src: "PR #185; Issue #172; Draft PR #179", lv: "2026-07-26", p: 54 }),

    rec({ n: 12, s: "creator-mini-media", t: "Creator Mini-Media", k: "크리에이터 미니미디어",
      a: NA.PROPOSED, l: "visual_reference", st: "review",
      ui: UI.IN_PROGRESS, ux: UX.BLOCKED_BY_UI, be: BE.FROZEN,
      pdi: 173, ci: 173, pr: 178,
      w: "reference/business-12-creator-mini-media-v1/",
      sty: "Visual reference in Draft PR", su: null, d: "Not deployed", rs: "not_released",
      gl: "Draft PR #178", gu: "https://github.com/skerishKang/ai-revenue-lab/pull/178",
      iu: "https://github.com/skerishKang/ai-revenue-lab/issues/173",
      ca: "Complete Phase 1 UI review", na: "Obtain exact-head CTO approval",
      kl: "PR #185 merged as canonical; registry doc conflict",
      src: "PR #185; Issue #173; Draft PR #178", lv: "2026-07-26", p: 52 }),

    // ═══════════════════════════════════════════════════════════
    // 13–14: CANONICAL — verified in BUSINESS_REGISTRY.md
    // ═══════════════════════════════════════════════════════════
    rec({ n: 13, s: "personal-video-archive", t: "Personal Video Archive", k: "나의 영상 아카이브",
      a: NA.CANONICAL, l: "private_preview", st: "review",
      ui: UI.APPROVED, ux: UX.NOT_STARTED, be: BE.DECISION_PENDING,
      pdi: 76, ci: 76, pr: 78,
      w: "apps/personal-video-archive/", sty: "Cloudflare Pages branch preview",
      su: "https://feat-personal-video-archive.ai-revenue-personal-video-archive.pages.dev",
      d: "Merged product preview", rs: "preview_draft",
      gl: "Merged PR #78", gu: "https://github.com/skerishKang/ai-revenue-lab/pull/78",
      iu: "https://github.com/skerishKang/ai-revenue-lab/issues/76",
      ca: "Verify merged preview", na: "Decide next production-infrastructure scope",
      kl: "Branch preview only; no fixed Production URL",
      src: "Issues #60, #62, #72, #76; PR #78", lv: "2026-07-24", p: 42 }),

    rec({ n: 14, s: "korean-ai-platform", t: "Korean AI Platform", k: "한국형 AI 실행 플랫폼",
      a: NA.CANONICAL, l: "private_preview", st: "running",
      ui: UI.APPROVED, ux: UX.NOT_STARTED, be: BE.IN_PROGRESS,
      pdi: 80, ci: 138, pr: 142,
      w: "apps/korean-ai-platform/", sty: "Cloudflare Worker",
      su: "https://ai-revenue-korean-ai-platform.charliekant.workers.dev/workspace",
      d: "PR #142 merged — dedicated Worker deployed", rs: "staging",
      gl: "PR #142 merged", gu: "https://github.com/skerishKang/ai-revenue-lab/pull/142",
      iu: "https://github.com/skerishKang/ai-revenue-lab/issues/138",
      ca: "Configure Provider registry", na: "Activate real BYOK chat",
      kl: "Provider registry not yet configured; real chat not yet active",
      src: "Issue #80, #138; PR #79, #142", lv: "2026-07-25", p: 92 }),

    // ═══════════════════════════════════════════════════════════
    // 15–22: PROPOSED-NUMBER — product-decision + Phase 1 UI issues exist
    // ═══════════════════════════════════════════════════════════
    rec({ n: 15, s: "global-ai-newsroom", t: "Global AI Newsroom", k: "글로벌 AI 뉴스룸",
      a: NA.PROPOSED, l: "visual_reference", st: "review",
      ui: UI.IN_PROGRESS, ux: UX.BLOCKED_BY_UI, be: BE.FROZEN,
      pdi: 187, ci: 187, pr: 194,
      w: "reference/business-15-global-ai-newsroom-v1/", sty: "Phase 1 UI in Draft PR",
      su: null, d: "Not deployed", rs: "not_released",
      gl: "Draft PR #194", gu: "https://github.com/skerishKang/ai-revenue-lab/pull/194",
      iu: "https://github.com/skerishKang/ai-revenue-lab/issues/187",
      ca: "Phase 1 UI review pending",
      na: "Obtain exact-head CTO approval",
      kl: "Product-decision Issue #187 open; BUSINESS_REGISTRY.md implicitly reserved",
      src: "Issues #187, #188; Draft PR #194", lv: "2026-07-29", p: 40 }),

    rec({ n: 16, s: "personal-sports", t: "Personal Sports", k: "나의 스포츠 채널",
      a: NA.PROPOSED, l: "visual_reference", st: "review",
      ui: UI.IN_PROGRESS, ux: UX.BLOCKED_BY_UI, be: BE.FROZEN,
      pdi: 189, ci: 189, pr: 195,
      w: "reference/business-16-personal-sports-v1/", sty: "Phase 1 UI in Draft PR",
      su: null, d: "Not deployed", rs: "not_released",
      gl: "Draft PR #195", gu: "https://github.com/skerishKang/ai-revenue-lab/pull/195",
      iu: "https://github.com/skerishKang/ai-revenue-lab/issues/189",
      ca: "Phase 1 UI review pending", na: "Obtain exact-head CTO approval",
      kl: "Product-decision Issue #189 open",
      src: "Issues #189, #190; Draft PR #195", lv: "2026-07-29", p: 38 }),

    rec({ n: 17, s: "local-shop-magazine", t: "Local Shop Magazine", k: "우리 가게 매거진",
      a: NA.PROPOSED, l: "visual_reference", st: "review",
      ui: UI.IN_PROGRESS, ux: UX.BLOCKED_BY_UI, be: BE.FROZEN,
      pdi: 191, ci: 191, pr: 233,
      w: "reference/business-17-local-shop-magazine-v1/", sty: "Phase 1 UI in Draft PR",
      su: null, d: "Not deployed", rs: "not_released",
      gl: "Draft PR #233", gu: "https://github.com/skerishKang/ai-revenue-lab/pull/233",
      iu: "https://github.com/skerishKang/ai-revenue-lab/issues/191",
      ca: "Phase 1 UI review pending", na: "Obtain exact-head CTO approval",
      kl: "Product-decision Issue #191 open",
      src: "Issues #191, #192; Draft PR #233", lv: "2026-07-29", p: 36 }),

    rec({ n: 18, s: "personal-audio-channel", t: "Personal Audio Channel", k: "나의 오디오 채널",
      a: NA.PROPOSED, l: "visual_reference", st: "review",
      ui: UI.IN_PROGRESS, ux: UX.BLOCKED_BY_UI, be: BE.FROZEN,
      pdi: 196, ci: 196, pr: 203,
      w: "reference/business-18-personal-audio-channel-v1/", sty: "Phase 1 UI in Draft PR",
      su: null, d: "Not deployed", rs: "not_released",
      gl: "Draft PR #203", gu: "https://github.com/skerishKang/ai-revenue-lab/pull/203",
      iu: "https://github.com/skerishKang/ai-revenue-lab/issues/196",
      ca: "Phase 1 UI review pending", na: "Obtain exact-head CTO approval",
      kl: "Product-decision Issue #196 open",
      src: "Issues #196, #197; Draft PR #203", lv: "2026-07-29", p: 34 }),

    rec({ n: 19, s: "personal-memory-book", t: "Personal Memory Book", k: "나의 기억책",
      a: NA.PROPOSED, l: "visual_reference", st: "review",
      ui: UI.IN_PROGRESS, ux: UX.BLOCKED_BY_UI, be: BE.FROZEN,
      pdi: 198, ci: 198, pr: 202,
      w: "reference/business-19-personal-memory-book-v1/", sty: "Phase 1 UI in Draft PR",
      su: null, d: "Not deployed", rs: "not_released",
      gl: "Draft PR #202", gu: "https://github.com/skerishKang/ai-revenue-lab/pull/202",
      iu: "https://github.com/skerishKang/ai-revenue-lab/issues/198",
      ca: "Phase 1 UI review pending", na: "Obtain exact-head CTO approval",
      kl: "Product-decision Issue #198 open",
      src: "Issues #198, #199; Draft PR #202", lv: "2026-07-29", p: 33 }),

    rec({ n: 20, s: "personal-memory-novel", t: "Personal Memory Novel", k: "나의 기억소설",
      a: NA.PROPOSED, l: "visual_reference", st: "review",
      ui: UI.IN_PROGRESS, ux: UX.BLOCKED_BY_UI, be: BE.FROZEN,
      pdi: 200, ci: 200, pr: 206,
      w: "reference/business-20-personal-memory-novel-v1/", sty: "Phase 1 UI in Draft PR",
      su: null, d: "Not deployed", rs: "not_released",
      gl: "Draft PR #206", gu: "https://github.com/skerishKang/ai-revenue-lab/pull/206",
      iu: "https://github.com/skerishKang/ai-revenue-lab/issues/200",
      ca: "Phase 1 UI review pending", na: "Obtain exact-head CTO approval",
      kl: "Product-decision Issue #200 open",
      src: "Issues #200, #201; Draft PR #206", lv: "2026-07-29", p: 31 }),

    rec({ n: 21, s: "founder-strategy-letter", t: "Founder Strategy Letter", k: "대표 전략 편지",
      a: NA.PROPOSED, l: "visual_reference", st: "review",
      ui: UI.IN_PROGRESS, ux: UX.BLOCKED_BY_UI, be: BE.FROZEN,
      pdi: 204, ci: 204, pr: 207,
      w: "reference/business-21-founder-strategy-letter-v1/", sty: "Phase 1 UI in Draft PR",
      su: null, d: "Not deployed", rs: "not_released",
      gl: "Draft PR #207", gu: "https://github.com/skerishKang/ai-revenue-lab/pull/207",
      iu: "https://github.com/skerishKang/ai-revenue-lab/issues/204",
      ca: "Phase 1 UI review pending", na: "Obtain exact-head CTO approval",
      kl: "Product-decision Issue #204 open",
      src: "Issues #204, #205; Draft PR #207", lv: "2026-07-29", p: 29 }),

    rec({ n: 22, s: "personal-media-studio", t: "Personal Media Studio", k: "개인 미디어 스튜디오",
      a: NA.PROPOSED, l: "visual_reference", st: "review",
      ui: UI.IN_PROGRESS, ux: UX.BLOCKED_BY_UI, be: BE.FROZEN,
      pdi: 222, ci: 222, pr: 224,
      w: "reference/business-22-personal-media-studio-v1/", sty: "Phase 1 UI in Draft PR",
      su: null, d: "Not deployed", rs: "not_released",
      gl: "Draft PR #224", gu: "https://github.com/skerishKang/ai-revenue-lab/pull/224",
      iu: "https://github.com/skerishKang/ai-revenue-lab/issues/222",
      ca: "Phase 1 UI review pending", na: "Obtain exact-head CTO approval",
      kl: "Product-decision Issue #222 open",
      src: "Issues #222, #223; Draft PR #224", lv: "2026-07-29", p: 28 }),

    // ═══════════════════════════════════════════════════════════
    // 23–25: EXISTING-PROJECT — separate repos exist
    // ═══════════════════════════════════════════════════════════
    rec({ n: 23, s: "lovebud", t: "LoveBud", k: "러브버드",
      a: NA.EXISTING_PROJECT, l: "active", st: "running",
      ui: UI.APPROVED, ux: UX.IN_PROGRESS, be: BE.IMPLEMENTED,
      ci: 3425, pr: 3531,
      w: "skerishKang/LoveBud", sty: "Cloudflare Pages",
      su: "https://lovebud.pages.dev/", d: "Live Cloudflare Pages deployment", rs: "live",
      gl: "Separate repository \u00b7 LoveBud",
      gu: "https://github.com/skerishKang/LoveBud",
      iu: "https://github.com/skerishKang/LoveBud/issues/3425",
      ca: "Architecture audit (#3425)", na: "Migration ledger and provenance gate (#3458)",
      kl: "Not assigned a canonical Business number; separate repository",
      src: "BUSINESS_CANDIDATE_BACKLOG.md; skerishKang/LoveBud", lv: "2026-07-26", p: 45 }),

    rec({ n: 24, s: "lovetree-3", t: "LoveTree 3.0", k: "러브트리 3.0",
      a: NA.EXISTING_PROJECT, l: "active", st: "running",
      ui: UI.APPROVED, ux: UX.NOT_STARTED, be: BE.IMPLEMENTED,
      w: "skerishKang/lovetree3.0", sty: "Cloudflare Pages",
      su: "https://lovetree3.pages.dev/", d: "Live Cloudflare Pages deployment", rs: "live",
      gl: "Separate repository \u00b7 lovetree3.0",
      gu: "https://github.com/skerishKang/lovetree3.0",
      ca: "Current work not defined (no verified milestone)",
      na: "Define feature expansion plan",
      kl: "Not assigned a canonical Business number; separate repository",
      src: "BUSINESS_CANDIDATE_BACKLOG.md; skerishKang/lovetree3.0", lv: "2026-07-26", p: 25 }),

    rec({ n: 25, s: "love-matchmaking", t: "Love Matchmaking", k: "러브 매치메이킹",
      a: NA.EXISTING_PROJECT, l: "concept", st: "planning",
      ui: UI.NOT_STARTED, ux: UX.BLOCKED_BY_UI, be: BE.FROZEN,
      w: "skerishKang/401-love-match-making",
      sty: null, su: null,
      d: "Repository exists; no implementation or deployment evidence", rs: "not_released",
      gl: "Separate repository \u00b7 401-love-match-making",
      gu: "https://github.com/skerishKang/401-love-match-making",
      ca: "No current work", na: "Define implementation scope",
      kl: "Not assigned a canonical Business number; separate repository; no deployed UI",
      src: "BUSINESS_CANDIDATE_BACKLOG.md; skerishKang/401-love-match-making",
      lv: "2026-07-26", p: 15 }),

    // ═══════════════════════════════════════════════════════════
    // 26–35: PROPOSED-NUMBER — product-decision + Phase 1 UI issues exist
    // ═══════════════════════════════════════════════════════════
    rec({ n: 26, s: "company-memory", t: "Company Memory", k: "회사 기억",
      a: NA.PROPOSED, l: "visual_reference", st: "review",
      ui: UI.IN_PROGRESS, ux: UX.BLOCKED_BY_UI, be: BE.FROZEN,
      pdi: 226, ci: 226, pr: 228,
      w: "reference/business-26-company-memory-v1/", sty: "Phase 1 UI in Draft PR",
      su: null, d: "Not deployed", rs: "not_released",
      gl: "Draft PR #228", gu: "https://github.com/skerishKang/ai-revenue-lab/pull/228",
      iu: "https://github.com/skerishKang/ai-revenue-lab/issues/226",
      ca: "Phase 1 UI review pending", na: "Obtain exact-head CTO approval",
      kl: "Product-decision Issue #226 open",
      src: "Issues #226, #227; Draft PR #228", lv: "2026-07-29", p: 27 }),

    rec({ n: 27, s: "evidence-studio", t: "Evidence Studio", k: "사건 기록실",
      a: NA.PROPOSED, l: "visual_reference", st: "review",
      ui: UI.IN_PROGRESS, ux: UX.BLOCKED_BY_UI, be: BE.FROZEN,
      pdi: 230, ci: 230, pr: 232,
      w: "reference/business-27-evidence-studio-v1/", sty: "Phase 1 UI in Draft PR",
      su: null, d: "Not deployed", rs: "not_released",
      gl: "Draft PR #232", gu: "https://github.com/skerishKang/ai-revenue-lab/pull/232",
      iu: "https://github.com/skerishKang/ai-revenue-lab/issues/230",
      ca: "Phase 1 UI review pending", na: "Obtain exact-head CTO approval",
      kl: "Product-decision Issue #230 open",
      src: "Issues #230, #231; Draft PR #232", lv: "2026-07-29", p: 26 }),

    rec({ n: 28, s: "decision-archive", t: "Decision Archive", k: "회의\u00b7결정 기록실",
      a: NA.PROPOSED, l: "visual_reference", st: "review",
      ui: UI.IN_PROGRESS, ux: UX.BLOCKED_BY_UI, be: BE.FROZEN,
      pdi: 234, ci: 234, pr: 239,
      w: "reference/business-28-decision-archive-v1/", sty: "Phase 1 UI in Draft PR",
      su: null, d: "Not deployed", rs: "not_released",
      gl: "Draft PR #239", gu: "https://github.com/skerishKang/ai-revenue-lab/pull/239",
      iu: "https://github.com/skerishKang/ai-revenue-lab/issues/234",
      ca: "Phase 1 UI review pending", na: "Obtain exact-head CTO approval",
      kl: "Product-decision Issue #234 open",
      src: "Issues #234, #235; Draft PR #239", lv: "2026-07-29", p: 24 }),

    rec({ n: 29, s: "apartment-governance", t: "Apartment Governance", k: "우리단지 운영실",
      a: NA.PROPOSED, l: "visual_reference", st: "review",
      ui: UI.IN_PROGRESS, ux: UX.BLOCKED_BY_UI, be: BE.FROZEN,
      pdi: 236, ci: 236, pr: 238,
      w: "reference/business-29-apartment-governance-v1/", sty: "Phase 1 UI in Draft PR",
      su: null, d: "Not deployed", rs: "not_released",
      gl: "Draft PR #238", gu: "https://github.com/skerishKang/ai-revenue-lab/pull/238",
      iu: "https://github.com/skerishKang/ai-revenue-lab/issues/236",
      ca: "Phase 1 UI review pending", na: "Obtain exact-head CTO approval",
      kl: "Product-decision Issue #236 open",
      src: "Issues #236, #237; Draft PR #238", lv: "2026-07-29", p: 22 }),

    rec({ n: 30, s: "civic-ai-navigator", t: "Civic AI Navigator", k: "시민 AI 내비게이터",
      a: NA.PROPOSED, l: "visual_reference", st: "review",
      ui: UI.IN_PROGRESS, ux: UX.BLOCKED_BY_UI, be: BE.FROZEN,
      pdi: 240, ci: 240, pr: 245,
      w: "reference/business-30-civic-ai-navigator-v1/", sty: "Phase 1 UI in Draft PR",
      su: null, d: "Not deployed", rs: "not_released",
      gl: "Draft PR #245", gu: "https://github.com/skerishKang/ai-revenue-lab/pull/245",
      iu: "https://github.com/skerishKang/ai-revenue-lab/issues/240",
      ca: "Phase 1 UI review pending", na: "Obtain exact-head CTO approval",
      kl: "Product-decision Issue #240 open",
      src: "Issues #240, #242; Draft PR #245", lv: "2026-07-29", p: 20 }),

    rec({ n: 31, s: "public-procedure-experience-data", t: "Public Procedure Experience Data", k: "공공절차 경험 데이터",
      a: NA.PROPOSED, l: "visual_reference", st: "review",
      ui: UI.IN_PROGRESS, ux: UX.BLOCKED_BY_UI, be: BE.FROZEN,
      pdi: 241, ci: 241, pr: 244,
      w: "reference/business-31-public-procedure-data-v1/", sty: "Phase 1 UI in Draft PR",
      su: null, d: "Not deployed", rs: "not_released",
      gl: "Draft PR #244", gu: "https://github.com/skerishKang/ai-revenue-lab/pull/244",
      iu: "https://github.com/skerishKang/ai-revenue-lab/issues/241",
      ca: "Phase 1 UI review pending", na: "Obtain exact-head CTO approval",
      kl: "Product-decision Issue #241 open",
      src: "Issues #241, #243; Draft PR #244", lv: "2026-07-29", p: 18 }),

    rec({ n: 32, s: "ai-skill-studio", t: "AI Skill Studio", k: "AI 업무 실습실",
      a: NA.PROPOSED, l: "visual_reference", st: "review",
      ui: UI.IN_PROGRESS, ux: UX.BLOCKED_BY_UI, be: BE.FROZEN,
      pdi: 246, ci: 246, pr: 251,
      w: "reference/business-32-ai-skill-studio-v1/", sty: "Phase 1 UI in Draft PR",
      su: null, d: "Not deployed", rs: "not_released",
      gl: "Draft PR #251", gu: "https://github.com/skerishKang/ai-revenue-lab/pull/251",
      iu: "https://github.com/skerishKang/ai-revenue-lab/issues/246",
      ca: "Phase 1 UI review pending", na: "Obtain exact-head CTO approval",
      kl: "Product-decision Issue #246 open",
      src: "Issues #246, #248; Draft PR #251", lv: "2026-07-29", p: 16 }),

    rec({ n: 33, s: "research-memory", t: "Research Memory", k: "연구 기억실",
      a: NA.PROPOSED, l: "visual_reference", st: "review",
      ui: UI.IN_PROGRESS, ux: UX.BLOCKED_BY_UI, be: BE.FROZEN,
      pdi: 247, ci: 247, pr: 250,
      w: "reference/business-33-research-memory-v1/", sty: "Phase 1 UI in Draft PR",
      su: null, d: "Not deployed", rs: "not_released",
      gl: "Draft PR #250", gu: "https://github.com/skerishKang/ai-revenue-lab/pull/250",
      iu: "https://github.com/skerishKang/ai-revenue-lab/issues/247",
      ca: "Phase 1 UI review pending", na: "Obtain exact-head CTO approval",
      kl: "Product-decision Issue #247 open",
      src: "Issues #247, #249; Draft PR #250", lv: "2026-07-29", p: 14 }),

    rec({ n: 34, s: "ai-dubbing-studio", t: "AI Dubbing Studio", k: "AI 더빙 스튜디오",
      a: NA.PROPOSED, l: "visual_reference", st: "review",
      ui: UI.IN_PROGRESS, ux: UX.BLOCKED_BY_UI, be: BE.FROZEN,
      pdi: 252, ci: 252, pr: 258,
      w: "reference/business-34-ai-dubbing-studio-v1/", sty: "Phase 1 UI in Draft PR",
      su: null, d: "Not deployed", rs: "not_released",
      gl: "Draft PR #258", gu: "https://github.com/skerishKang/ai-revenue-lab/pull/258",
      iu: "https://github.com/skerishKang/ai-revenue-lab/issues/252",
      ca: "Phase 1 UI review pending", na: "Obtain exact-head CTO approval",
      kl: "Product-decision Issue #252 open",
      src: "Issues #252, #254; Draft PR #258", lv: "2026-07-29", p: 12 }),

    rec({ n: 35, s: "ai-media-education-dx", t: "AI Media Education & DX", k: "AI 미디어 교육\u00b7DX",
      a: NA.PROPOSED, l: "visual_reference", st: "review",
      ui: UI.IN_PROGRESS, ux: UX.BLOCKED_BY_UI, be: BE.FROZEN,
      pdi: 253, ci: 253, pr: 257,
      w: "reference/business-35-ai-media-education-dx-v1/", sty: "Phase 1 UI in Draft PR",
      su: null, d: "Not deployed", rs: "not_released",
      gl: "Draft PR #257", gu: "https://github.com/skerishKang/ai-revenue-lab/pull/257",
      iu: "https://github.com/skerishKang/ai-revenue-lab/issues/253",
      ca: "Phase 1 UI review pending", na: "Obtain exact-head CTO approval",
      kl: "Product-decision Issue #253 open",
      src: "Issues #253, #255; Draft PR #257", lv: "2026-07-29", p: 11 }),

    // ═══════════════════════════════════════════════════════════
    // 36–43: PROPOSED-NUMBER — product-decision + Phase 1 UI issues
    // ═══════════════════════════════════════════════════════════
    rec({ n: 36, s: "ai-women-safety", t: "AI Women Safety", k: "AI 여성안전 서비스",
      a: NA.PROPOSED, l: "visual_reference", st: "review",
      ui: UI.IN_PROGRESS, ux: UX.BLOCKED_BY_UI, be: BE.FROZEN,
      pdi: 266, ci: 268, pr: 279,
      w: "reference/business-36-ai-women-safety-v1/", sty: "Phase 1 UI in Draft PR",
      su: null, d: "Not deployed", rs: "not_released",
      gl: "Draft PR #279", gu: "https://github.com/skerishKang/ai-revenue-lab/pull/279",
      iu: "https://github.com/skerishKang/ai-revenue-lab/issues/268",
      ca: "Phase 1 UI review pending", na: "Obtain exact-head CTO approval",
      kl: "Product-decision Issue #266 open",
      src: "Issues #266, #268; Draft PR #279", lv: "2026-07-29", p: 50 }),

    rec({ n: 37, s: "ai-safe-route", t: "AI Safe Route", k: "AI 안전경로",
      a: NA.PROPOSED, l: "visual_reference", st: "review",
      ui: UI.IN_PROGRESS, ux: UX.BLOCKED_BY_UI, be: BE.FROZEN,
      pdi: 259, ci: 259, pr: 264,
      w: "reference/business-37-ai-safe-route-v1/", sty: "Phase 1 UI in Draft PR",
      su: null, d: "Not deployed", rs: "not_released",
      gl: "Draft PR #264", gu: "https://github.com/skerishKang/ai-revenue-lab/pull/264",
      iu: "https://github.com/skerishKang/ai-revenue-lab/issues/259",
      ca: "Phase 1 UI review pending", na: "Obtain exact-head CTO approval",
      kl: "Product-decision Issue #259 open",
      src: "Issues #259, #260; Draft PR #264", lv: "2026-07-29", p: 46 }),

    rec({ n: 38, s: "ai-exercise-coach", t: "AI Exercise Coach", k: "AI 운동 코치",
      a: NA.PROPOSED, l: "visual_reference", st: "review",
      ui: UI.IN_PROGRESS, ux: UX.BLOCKED_BY_UI, be: BE.FROZEN,
      pdi: 267, ci: 269, pr: 278,
      w: "reference/business-38-ai-exercise-coach-v1/", sty: "Phase 1 UI in Draft PR",
      su: null, d: "Not deployed", rs: "not_released",
      gl: "Draft PR #278", gu: "https://github.com/skerishKang/ai-revenue-lab/pull/278",
      iu: "https://github.com/skerishKang/ai-revenue-lab/issues/269",
      ca: "Phase 1 UI review pending", na: "Obtain exact-head CTO approval",
      kl: "Product-decision Issues #267, #269 open",
      src: "Issues #267, #269; Draft PR #278", lv: "2026-07-29", p: 48 }),

    rec({ n: 39, s: "112-real-time-interpretation", t: "112 Real-Time Interpretation", k: "112 실시간 AI 통역",
      a: NA.PROPOSED, l: "visual_reference", st: "review",
      ui: UI.IN_PROGRESS, ux: UX.BLOCKED_BY_UI, be: BE.FROZEN,
      pdi: 261, ci: 261, pr: 265,
      w: "reference/business-39-112-interpretation-v1/", sty: "Phase 1 UI in Draft PR",
      su: null, d: "Not deployed", rs: "not_released",
      gl: "Draft PR #265", gu: "https://github.com/skerishKang/ai-revenue-lab/pull/265",
      iu: "https://github.com/skerishKang/ai-revenue-lab/issues/261",
      ca: "Phase 1 UI review pending", na: "Obtain exact-head CTO approval",
      kl: "Product-decision Issue #261 open",
      src: "Issues #261, #262; Draft PR #265", lv: "2026-07-29", p: 44 }),

    rec({ n: 40, s: "emergency-urgency-ai", t: "Emergency Urgency AI", k: "긴급도 판단 AI",
      a: NA.PROPOSED, l: "visual_reference", st: "review",
      ui: UI.IN_PROGRESS, ux: UX.BLOCKED_BY_UI, be: BE.FROZEN,
      pdi: 270, ci: 270, pr: 281,
      w: "reference/business-40-emergency-urgency-ai-v1/", sty: "Phase 1 UI in Draft PR",
      su: null, d: "Not deployed", rs: "not_released",
      gl: "Draft PR #281", gu: "https://github.com/skerishKang/ai-revenue-lab/pull/281",
      iu: "https://github.com/skerishKang/ai-revenue-lab/issues/270",
      ca: "Phase 1 UI review pending", na: "Obtain exact-head CTO approval",
      kl: "Product-decision Issue #270 open",
      src: "Issues #270, #272; Draft PR #281", lv: "2026-07-29", p: 10 }),

    rec({ n: 41, s: "foreign-emergency-assistant", t: "Foreign Emergency Assistant", k: "외국인 긴급신고 도우미",
      a: NA.PROPOSED, l: "visual_reference", st: "review",
      ui: UI.IN_PROGRESS, ux: UX.BLOCKED_BY_UI, be: BE.FROZEN,
      pdi: 271, ci: 271, pr: 283,
      w: "reference/business-41-foreign-emergency-assistant-v1/", sty: "Phase 1 UI in Draft PR",
      su: null, d: "Not deployed", rs: "not_released",
      gl: "Draft PR #283", gu: "https://github.com/skerishKang/ai-revenue-lab/pull/283",
      iu: "https://github.com/skerishKang/ai-revenue-lab/issues/271",
      ca: "Phase 1 UI review pending", na: "Obtain exact-head CTO approval",
      kl: "Product-decision Issue #271 open",
      src: "Issues #271, #273; Draft PR #283", lv: "2026-07-29", p: 8 }),

    rec({ n: 42, s: "ai-development-control-tower", t: "AI Development Control Tower", k: "AI 개발 관제실",
      a: NA.PROPOSED, l: "visual_reference", st: "review",
      ui: UI.IN_PROGRESS, ux: UX.BLOCKED_BY_UI, be: BE.FROZEN,
      pdi: 274, ci: 274, pr: null,
      w: "reference/business-42-ai-development-control-tower-v1/", sty: "Phase 1 UI branch only",
      su: null, d: "Not deployed", rs: "not_released",
      gl: "Branch exists; no PR yet",
      gu: "https://github.com/skerishKang/ai-revenue-lab/tree/feat/business-42-ai-development-control-tower-ui",
      iu: "https://github.com/skerishKang/ai-revenue-lab/issues/274",
      ca: "Phase 1 UI review pending", na: "Create Draft PR and obtain CTO approval",
      kl: "Product-decision Issue #274 open; UI issue #276 open; no PR yet",
      src: "Issues #274, #276; origin/feat/business-42-ai-development-control-tower-ui",
      lv: "2026-07-29", p: 6 }),

    rec({ n: 43, s: "ai-software-factory", t: "AI Software Factory", k: "AI 소프트웨어 공장",
      a: NA.PROPOSED, l: "visual_reference", st: "review",
      ui: UI.IN_PROGRESS, ux: UX.BLOCKED_BY_UI, be: BE.FROZEN,
      pdi: 275, ci: 275, pr: 284,
      w: "reference/business-43-ai-software-factory-v1/", sty: "Phase 1 UI in Draft PR",
      su: null, d: "Not deployed", rs: "not_released",
      gl: "Draft PR #284", gu: "https://github.com/skerishKang/ai-revenue-lab/pull/284",
      iu: "https://github.com/skerishKang/ai-revenue-lab/issues/275",
      ca: "Phase 1 UI review pending", na: "Obtain exact-head CTO approval",
      kl: "Product-decision Issue #275 open",
      src: "Issues #275, #277; Draft PR #284", lv: "2026-07-29", p: 4 }),

    // ═══════════════════════════════════════════════════════════
    // 44: EXISTING-PROJECT — this IS the Portfolio Console
    // ═══════════════════════════════════════════════════════════
    rec({ n: 44, s: "portfolio-operations-console", t: "Portfolio Operations Console", k: "포트폴리오 운영 콘솔",
      a: NA.EXISTING_PROJECT, l: "active", st: "running",
      ui: UI.APPROVED, ux: UX.NOT_STARTED, be: BE.NOT_APPLICABLE,
      w: "apps/portfolio-console/", sty: "Cloudflare Pages",
      su: "https://ai-revenue-portfolio-console.pages.dev",
      d: "Cloudflare Pages deployment (Access-protected)", rs: "live",
      gl: "This console", gu: "https://github.com/skerishKang/ai-revenue-lab",
      iu: "https://github.com/skerishKang/ai-revenue-lab/issues/117",
      ca: "This Business IS the Portfolio Console running now",
      na: "GitHub live-sync activation (#163); ongoing improvements",
      kl: "Not a canonical numbered Business; this is the console itself",
      src: "BUSINESS_CANDIDATE_BACKLOG.md (existing-project); Portfolio Console application",
      lv: "2026-07-29", p: 5 }),

    // ═══════════════════════════════════════════════════════════
    // 45–55: CANDIDATE — from backlog, no product-decision issues confirmed
    // ═══════════════════════════════════════════════════════════
    rec({ n: 45, s: "ai-content-engine", t: "AI Content Engine", k: "AI 콘텐츠 엔진", a: NA.CANDIDATE, src: "BUSINESS_CANDIDATE_BACKLOG.md" }),
    rec({ n: 46, s: "ai-personalization-engine", t: "AI Personalization Engine", k: "AI 개인화 엔진", a: NA.CANDIDATE, src: "BUSINESS_CANDIDATE_BACKLOG.md" }),
    rec({ n: 47, s: "real-time-feedback-engine", t: "Real-Time Feedback Engine", k: "실시간 반응 엔진", a: NA.CANDIDATE, src: "BUSINESS_CANDIDATE_BACKLOG.md" }),
    rec({ n: 48, s: "ai-verification-engine", t: "AI Verification Engine", k: "AI 검증\u00b7승인 엔진", a: NA.CANDIDATE, src: "BUSINESS_CANDIDATE_BACKLOG.md" }),
    rec({ n: 49, s: "public-data-connector-hub", t: "Public Data Connector Hub", k: "공공데이터 커넥터 허브", a: NA.CANDIDATE, src: "BUSINESS_CANDIDATE_BACKLOG.md" }),
    rec({ n: 50, s: "private-data-connector-hub", t: "Private Data Connector Hub", k: "사내자료 커넥터 허브", a: NA.CANDIDATE, src: "BUSINESS_CANDIDATE_BACKLOG.md" }),
    rec({ n: 51, s: "ai-workflow-marketplace", t: "AI Workflow Marketplace", k: "AI 워크플로우 마켓", a: NA.CANDIDATE, src: "BUSINESS_CANDIDATE_BACKLOG.md" }),
    rec({ n: 52, s: "scheduled-agent-operations", t: "Scheduled Agent Operations", k: "예약형 AI 운영", a: NA.CANDIDATE, src: "BUSINESS_CANDIDATE_BACKLOG.md" }),
    rec({ n: 53, s: "embedded-ai-sdk", t: "Embedded AI SDK", k: "임베드 AI SDK", a: NA.CANDIDATE, src: "BUSINESS_CANDIDATE_BACKLOG.md" }),
    rec({ n: 54, s: "ai-model-router", t: "AI Model Router", k: "AI 모델 라우터", a: NA.CANDIDATE, src: "BUSINESS_CANDIDATE_BACKLOG.md" }),
    rec({ n: 55, s: "local-ai-fleet", t: "Local AI Fleet", k: "로컬 AI 플릿", a: NA.CANDIDATE, src: "BUSINESS_CANDIDATE_BACKLOG.md" })
  ];
})();
