window.ARL_BUSINESSES = [
  {
    number: 1,
    slug: "personal-edition",
    title: "Personal Edition",
    koreanTitle: "퍼스널 에디션",
    state: "review",
    lifecycle: "private_preview",
    progress: 82,
    workspace: "apps/personal-edition/",
    surfaceType: "Cloudflare Pages branch preview",
    surfaceUrl: "https://feat-personal-edition-final.ai-revenue-personal-edition.pages.dev",
    deployment: "Preview deployed; CTO changes required",
    githubLabel: "Draft PR #111",
    githubUrl: "https://github.com/skerishKang/ai-revenue-lab/pull/111",
    issueUrl: "https://github.com/skerishKang/ai-revenue-lab/issues/108",
    nextAction: "Fix the current visual and clickable-flow blockers, then re-review PR #111.",
    lastVerified: "2026-07-24",
    priority: 100
  },
  {
    number: 2,
    slug: "living-travel",
    title: "Living Travel",
    koreanTitle: "리빙 트래블",
    state: "running",
    lifecycle: "private_preview",
    progress: 100,
    workspace: "apps/living-travel/",
    surfaceType: "External staging",
    surfaceUrl: "https://ops-living-travel-external-s.ai-revenue-living-travel.pages.dev",
    deployment: "Cloudflare Pages + Modal + Neon",
    githubLabel: "Merged PR #88",
    githubUrl: "https://github.com/skerishKang/ai-revenue-lab/pull/88",
    issueUrl: "https://github.com/skerishKang/ai-revenue-lab/issues/43",
    nextAction: "Prepare a resettable 60–90 second traveler/operator demo sequence.",
    lastVerified: "2026-07-24",
    priority: 35
  },
  {
    number: 3,
    slug: "living-fiction",
    title: "Living Fiction",
    koreanTitle: "리빙 픽션",
    state: "running",
    lifecycle: "private_preview",
    progress: 100,
    workspace: "apps/living-fiction/",
    surfaceType: "Modal production workflow",
    surfaceUrl: "https://padiemipu--ai-revenue-living-fiction-web.modal.run",
    deployment: "Modal + Neon",
    githubLabel: "Merged PR #85",
    githubUrl: "https://github.com/skerishKang/ai-revenue-lab/pull/85",
    issueUrl: "https://github.com/skerishKang/ai-revenue-lab/issues/55",
    nextAction: "Document synthetic invite credentials and the demo-data reset procedure.",
    lastVerified: "2026-07-24",
    priority: 32
  },
  {
    number: 4,
    slug: "living-learning",
    title: "Living Learning",
    koreanTitle: "리빙 러닝",
    state: "running",
    lifecycle: "private_preview",
    progress: 100,
    workspace: "apps/living-learning/",
    surfaceType: "Cloudflare Pages static demo",
    surfaceUrl: "https://ai-revenue-living-learning.pages.dev/",
    deployment: "Static preview available",
    githubLabel: "Merged PR #94",
    githubUrl: "https://github.com/skerishKang/ai-revenue-lab/pull/94",
    issueUrl: "https://github.com/skerishKang/ai-revenue-lab/issues/37",
    nextAction: "Standardize the first-lesson → adapted-lesson demo narration.",
    lastVerified: "2026-07-24",
    priority: 30
  },
  {
    number: 5,
    slug: "neighbor-market",
    title: "Neighbor Market",
    koreanTitle: "우리단지 이웃가게",
    state: "review",
    lifecycle: "concept",
    progress: 72,
    workspace: "reference/business-05-neighbor-market-v2/",
    surfaceType: "Static demo in Draft PR",
    surfaceUrl: null,
    deployment: "Assignment pending; no production deployment",
    githubLabel: "Draft PR #109",
    githubUrl: "https://github.com/skerishKang/ai-revenue-lab/pull/109",
    issueUrl: "https://github.com/skerishKang/ai-revenue-lab/issues/99",
    nextAction: "Accept the canonical Business 5 assignment and complete static-demo review.",
    lastVerified: "2026-07-24",
    priority: 95
  },
  {
    number: 6,
    slug: "world-feed",
    title: "World Feed",
    koreanTitle: "월드 피드",
    state: "planning",
    lifecycle: "number_reconciliation_required",
    progress: 35,
    workspace: "apps/world-feed/",
    surfaceType: "Research workspace",
    surfaceUrl: null,
    deployment: "Not assigned as canonical Business 6",
    githubLabel: "Issue #98",
    githubUrl: "https://github.com/skerishKang/ai-revenue-lab/issues/98",
    issueUrl: "https://github.com/skerishKang/ai-revenue-lab/issues/98",
    nextAction: "Approve, reject, or revise the proposed Business 6 mapping.",
    lastVerified: "2026-07-24",
    priority: 88
  },
  ...Array.from({ length: 6 }, (_, index) => {
    const number = index + 7;
    return {
      number,
      slug: `reserved-${String(number).padStart(2, "0")}`,
      title: "Reserved",
      koreanTitle: "미배정",
      state: "reserved",
      lifecycle: "reserved",
      progress: 0,
      workspace: "—",
      surfaceType: "—",
      surfaceUrl: null,
      deployment: "No assignment",
      githubLabel: "—",
      githubUrl: null,
      issueUrl: null,
      nextAction: "Assign only after an explicit product and numbering decision.",
      lastVerified: "2026-07-24",
      priority: 0
    };
  }),
  {
    number: 13,
    slug: "personal-video-archive",
    title: "Personal Video Archive",
    koreanTitle: "나의 영상 아카이브",
    state: "running",
    lifecycle: "private_preview",
    progress: 100,
    workspace: "apps/personal-video-archive/",
    surfaceType: "Cloudflare Pages branch preview",
    surfaceUrl: "https://feat-personal-video-archive.ai-revenue-personal-video-archive.pages.dev",
    deployment: "Merged product preview",
    githubLabel: "Merged PR #78",
    githubUrl: "https://github.com/skerishKang/ai-revenue-lab/pull/78",
    issueUrl: "https://github.com/skerishKang/ai-revenue-lab/issues/76",
    nextAction: "Verify the merged preview and decide the next production-infrastructure scope.",
    lastVerified: "2026-07-24",
    priority: 42
  },
  {
    number: 14,
    slug: "korean-ai-platform",
    title: "Korean AI Platform",
    koreanTitle: "한국형 AI 실행 플랫폼",
    state: "review",
    lifecycle: "private_preview",
    progress: 50,
    workspace: "apps/korean-ai-platform/",
    surfaceType: "Cloudflare Worker",
    surfaceUrl: null,
    deployment: "PR #142 merged — dedicated Worker deployed",
    githubLabel: "PR #142 merged",
    githubUrl: "https://github.com/skerishKang/ai-revenue-lab/pull/142",
    issueUrl: "https://github.com/skerishKang/ai-revenue-lab/issues/138",
    nextAction: "Configure Provider registry and activate real BYOK chat",
    lastVerified: "2026-07-25",
    priority: 92
  },
  {
    number: 15,
    slug: "unassigned-15",
    title: "Unassigned",
    koreanTitle: "미배정",
    state: "reserved",
    lifecycle: "reserved",
    progress: 0,
    workspace: "—",
    surfaceType: "—",
    surfaceUrl: null,
    deployment: "Open slot",
    githubLabel: "—",
    githubUrl: null,
    issueUrl: null,
    nextAction: "Define Business 15 only when a product decision is documented.",
    lastVerified: "2026-07-24",
    priority: 0
  }
];
