window.ARL_IDEAS = [
  { id:'BIO-001', domain:'Bio / medical training', title:'NIR Vein Intelligence → AI Venipuncture Training & Assessment', koreanTitle:'AI 정맥주사 실습·평가 시스템', status:'RESEARCHING', summary:'NIR 혈관 영상을 하나의 sensing layer로 사용해 어려운 혈관 사례의 시각화·접근부위 분석과 학습자 술기 평가를 객관화합니다.', note:'2026 revalidation verdict=NARROW. Generic clinical vein finder thesis killed; public-data software benchmark next. Hardware/patient-use claims HOLD.' },
  { id:'BIO-002', domain:'Healthcare AI governance', title:'Clinical AI Egress Control Plane', koreanTitle:'의료 생성형 AI 외부전송 안전·통제 계층', status:'PAUSED', summary:'병원 데이터가 외부·내부 생성형 AI로 나갈 때 임상 맥락과 준식별자까지 고려해 전송 정책을 통제합니다.', note:'B63 proposed / concept demo complete / hospital-HIS validation pending.' },
  { id:'BIO-003', domain:'Clinical longitudinal intelligence', title:'Longitudinal Patient CareGraph', koreanTitle:'장기 환자 케어그래프', status:'IDEA', summary:'흩어진 장기 의료기록과 진료 이벤트를 근거 연결형 환자 여정 그래프로 구성합니다.', note:'중복·현장 워크플로우 screening 필요.' },
  { id:'BIO-004', domain:'Patient communication', title:'Patient Communication AI', koreanTitle:'환자 커뮤니케이션 AI', status:'IDEA', summary:'복잡한 진료정보를 환자의 언어·이해수준·채널에 맞게 설명하되 원문 근거를 유지합니다.', note:'진단·치료 권한을 주장하지 않는 경계 필요.' },
  { id:'BIO-005', domain:'Preventive health', title:'Health-check Trend AI', koreanTitle:'건강검진 추세 AI', status:'IDEA', summary:'반복 건강검진 결과의 장기 변화를 추적하고 의미 있는 변화와 후속 확인 필요 항목을 근거와 함께 보여줍니다.', note:'의료 해석 및 규제 경계 screening 필요.' },
  { id:'BIO-006', domain:'Clinical workflow', title:'Ambient Medical AI / Scribe', koreanTitle:'앰비언트 의료 기록 AI', status:'DEPRIORITIZED', summary:'진료 대화를 구조화해 의료진 검토 가능한 기록으로 만드는 워크플로우입니다.', note:'혼잡한 시장과 낮은 차별성 때문에 현재 후순위.' },
  { id:'BIO-007', domain:'Rehab / movement', title:'Rehab / Pose AI', koreanTitle:'재활·자세 분석 AI', status:'SCREENING', summary:'자세·동작 분석을 재활 또는 운동 피드백 흐름에 연결합니다.', note:'기존 Business 38 AI Exercise Coach와 중복 여부 확인 필요.' },
  { id:'BIO-008', domain:'Biotech', title:'AI Drug Discovery', koreanTitle:'AI 신약개발', status:'DEPRIORITIZED', summary:'신약 연구 후보 탐색·랭킹에 AI를 적용하는 광범위한 후보입니다.', note:'현재 파디엠의 첫 진입영역으로는 범위와 도메인 자본 요구가 큼.' },
  { id:'BIO-009', domain:'Medical imaging', title:'Radiology Diagnosis AI', koreanTitle:'영상의학 진단보조 AI', status:'DEPRIORITIZED', summary:'의료영상 해석 또는 진단보조에 멀티모달 AI를 적용하는 후보입니다.', note:'경쟁·규제 강도가 높고 현재 차별근거가 약함.' },
  { id:'BIO-010', domain:'Genomics', title:'Genomics AI', koreanTitle:'유전체 AI', status:'DEPRIORITIZED', summary:'유전체 해석과 연구 워크플로우에 AI를 적용하는 후보입니다.', note:'전문 데이터·도메인 역량 확보 전까지 후순위.' },
  { id:'BIO-011', domain:'Clinical documents', title:'Medical Record Intelligence Workspace', koreanTitle:'의료기록 인텔리전스 워크스페이스', status:'IDEA', summary:'의료문서·근거·버전·검토상태를 하나의 source-grounded 작업공간으로 연결합니다.', note:'Living Archive / Research Memory / B63와 경계 screening 필요.' },
  { id:'BIO-012', domain:'Global healthcare', title:'Foreign Patient Medical Coordination', koreanTitle:'외국인 환자 의료 코디네이션 AI', status:'IDEA', summary:'다국어 의료문서·예약·설명·기관 간 인계를 하나의 환자 흐름으로 조정합니다.', note:'PADIEM 다국어 음성·번역 자산 재사용 가능성 검토.' },
  { id:'BIO-013', domain:'Biotech R&D operations', title:'Bio Evidence Graph', koreanTitle:'바이오 연구 증거그래프·재현성 코파일럿', status:'IDEA', summary:'연구결론을 실험·샘플·프로토콜·원시데이터·분석·보고서까지 역추적하고 증거 단절을 표시합니다.', note:'ELN/LIMS/Scientific Data Management 경쟁 screening 필요.' },
  { id:'GEN-001', domain:'Export / compliance', title:'AI Global Certification Passport', koreanTitle:'AI 글로벌 인증 패스포트', status:'IDEA', summary:'한국 기업 제품의 국가별 인증·규제 누락과 증빙 부족, 다음 행동을 제품 단위로 보여줍니다.', note:'Bio R&D 밖의 일반 포트폴리오 후보. Business 번호 미부여.' },
  { id:'GEN-002', domain:'Funding discovery', title:'Support Program AI Matching', koreanTitle:'지원사업 AI 매칭', status:'DUPLICATE', summary:'기업 조건과 공개 지원사업을 매칭하고 지원 가능성·준비사항을 설명합니다.', note:'400-ai-finder / cwtree 기존 작업과 중복. 신규 Business로 재제안 금지.' }
];
