window.ARL_PROJECTS = [
  {
    id: "portfolio-console",
    name: "Portfolio Console",
    koreanName: "포트폴리오 콘솔",
    businessNumber: null,
    purpose: "AI Revenue Lab의 모든 프로젝트와 Business를 한 화면에서 확인하는 개인용 관리 콘솔입니다.",
    repositoryLabel: "skerishKang/ai-revenue-lab",
    repositoryUrl: "https://github.com/skerishKang/ai-revenue-lab",
    workspace: "apps/portfolio-console/",
    pageUrl: "https://ai-revenue-portfolio-console.pages.dev",
    stage: "live",
    progressNote: "Cloudflare Pages에 배포 완료. Cloudflare Access 인증 후 접근 가능.",
    currentWork: "Project Directory 기능 추가 (Issue #132)",
    nextAction: "Project Directory 검증 후 병합",
    lastVerified: "2026-07-25"
  },
  {
    id: "lovebud",
    name: "LoveBud",
    koreanName: "러브버드",
    businessNumber: null,
    purpose: "커플·가족의 일상 기록과 공유를 위한 개인용 웹 서비스입니다.",
    repositoryLabel: "skerishKang/LoveBud",
    repositoryUrl: "https://github.com/skerishKang/LoveBud",
    workspace: "/",
    pageUrl: "https://lovebud.pages.dev/",
    stage: "live",
    progressNote: "Cloudflare Pages에 배포 완료.",
    currentWork: "현재 작업 없음",
    nextAction: "기능 확장 계획 수립",
    lastVerified: "2026-07-25"
  },
  {
    id: "personal-edition",
    name: "Personal Edition",
    koreanName: "퍼스널 에디션",
    businessNumber: 1,
    purpose: "개인 맞춤형 AI 어시스턴트 서비스의 프로토타입입니다.",
    repositoryLabel: "skerishKang/ai-revenue-lab",
    repositoryUrl: "https://github.com/skerishKang/ai-revenue-lab",
    workspace: "apps/personal-edition/",
    pageUrl: "https://feat-personal-edition-final.ai-revenue-personal-edition.pages.dev",
    stage: "review",
    progressNote: "Draft PR #111 검토 중. CTO 변경 요청 대기.",
    currentWork: "시각 및 클릭 흐름 차단 요소 수정",
    nextAction: "PR #111 재검토",
    lastVerified: "2026-07-24"
  },
  {
    id: "living-travel",
    name: "Living Travel",
    koreanName: "리빙 트래블",
    businessNumber: 2,
    purpose: "여행자·운영자용 AI 여행 계획 및 실행 서비스입니다.",
    repositoryLabel: "skerishKang/ai-revenue-lab",
    repositoryUrl: "https://github.com/skerishKang/ai-revenue-lab",
    workspace: "apps/living-travel/",
    pageUrl: "https://ops-living-travel-external-s.ai-revenue-living-travel.pages.dev",
    stage: "live",
    progressNote: "Cloudflare Pages + Modal + Neon 스택으로 배포 완료.",
    currentWork: "현재 작업 없음",
    nextAction: "60–90초 데모 시퀀스 준비",
    lastVerified: "2026-07-24"
  },
  {
    id: "living-fiction",
    name: "Living Fiction",
    koreanName: "리빙 픽션",
    businessNumber: 3,
    purpose: "AI 기반 인터랙티브 소설·스토리 생성 서비스입니다.",
    repositoryLabel: "skerishKang/ai-revenue-lab",
    repositoryUrl: "https://github.com/skerishKang/ai-revenue-lab",
    workspace: "apps/living-fiction/",
    pageUrl: null,
    stage: "live",
    progressNote: "기존 Modal 배포 주소가 응답하지 않아(404) 배포 재검증이 필요함.",
    currentWork: "현재 작업 없음",
    nextAction: "합성 초대 자격 증명 및 데모 데이터 초기화 절차 문서화",
    lastVerified: "2026-07-24"
  },
  {
    id: "living-learning",
    name: "Living Learning",
    koreanName: "리빙 러닝",
    businessNumber: 4,
    purpose: "AI 적응형 학습·레슨 생성 서비스입니다.",
    repositoryLabel: "skerishKang/ai-revenue-lab",
    repositoryUrl: "https://github.com/skerishKang/ai-revenue-lab",
    workspace: "apps/living-learning/",
    pageUrl: "https://ai-revenue-living-learning.pages.dev/",
    stage: "live",
    progressNote: "Cloudflare Pages 정적 데모로 배포 완료.",
    currentWork: "현재 작업 없음",
    nextAction: "첫 레슨 → 적응형 레슨 데모 내레이션 표준화",
    lastVerified: "2026-07-24"
  },
  {
    id: "personal-video-archive",
    name: "Personal Video Archive",
    koreanName: "나의 영상 아카이브",
    businessNumber: 13,
    purpose: "개인 영상 컬렉션의 아카이빙 및 검색 서비스입니다.",
    repositoryLabel: "skerishKang/ai-revenue-lab",
    repositoryUrl: "https://github.com/skerishKang/ai-revenue-lab",
    workspace: "apps/personal-video-archive/",
    pageUrl: "https://feat-personal-video-archive.ai-revenue-personal-video-archive.pages.dev",
    stage: "demo",
    progressNote: "병합된 브랜치 프리뷰로 배포 완료.",
    currentWork: "현재 작업 없음",
    nextAction: "병합된 프리뷰 검증 및 다음 프로덕션 인프라 범위 결정",
    lastVerified: "2026-07-24"
  },
  {
    id: "lovetree-3",
    name: "LoveTree 3.0",
    koreanName: "러브트리 3.0",
    businessNumber: null,
    purpose: "가계도·가족 관계 시각화 및 관리 서비스의 3세대 버전입니다.",
    repositoryLabel: "skerishKang/lovetree3.0",
    repositoryUrl: "https://github.com/skerishKang/lovetree3.0",
    workspace: "/",
    pageUrl: "https://lovetree3.pages.dev/",
    stage: "live",
    progressNote: "Cloudflare Pages에 배포 완료.",
    currentWork: "현재 작업 없음",
    nextAction: "기능 확장 계획 수립",
    lastVerified: "2026-07-25"
  },
  {
    id: "korean-ai-platform",
    name: "Korean AI Platform",
    koreanName: "한국형 AI 실행 플랫폼",
    businessNumber: 14,
    purpose: "한국어 특화 AI 실행 환경 및 BYOK(Bring Your Own Key) 게이트웨이입니다.",
    repositoryLabel: "skerishKang/ai-revenue-lab",
    repositoryUrl: "https://github.com/skerishKang/ai-revenue-lab",
    workspace: "apps/korean-ai-platform/",
    pageUrl: null,
    stage: "build",
    progressNote: "Phase 2 다중 Provider BYOK 라우팅이 PR #133으로 병합됨. Phase 3 한국어 세션 워크스페이스는 Draft PR #136에서 진행 중. 승인된 전용 배포 주소 없음.",
    currentWork: "Phase 3 한국어 우선 세션 워크스페이스 검토 및 안정화",
    nextAction: "PR #136의 CTO 검토 사항을 완료하고 병합 여부 결정",
    lastVerified: "2026-07-25"
  },
  {
    id: "ai-finder-bukgu",
    name: "AI Finder / 광주 북구청",
    koreanName: "AI 파인더 / 광주 북구청",
    businessNumber: null,
    purpose: "광주 북구청 대상 AI 기반 정보 검색·안내 서비스입니다.",
    repositoryLabel: "skerishKang/400-ai-finder",
    repositoryUrl: "https://github.com/skerishKang/400-ai-finder",
    workspace: "/",
    pageUrl: "https://cgbukku.pages.dev/",
    stage: "live",
    progressNote: "Cloudflare Pages에 배포 완료.",
    currentWork: "현재 작업 없음",
    nextAction: "기능 확장 계획 수립",
    lastVerified: "2026-07-25"
  },
  {
    id: "love-matchmaking",
    name: "Love Matchmaking",
    koreanName: "러브 매치메이킹",
    businessNumber: null,
    purpose: "AI 기반 매칭·소개 서비스 컨셉입니다.",
    repositoryLabel: "skerishKang/401-love-match-making",
    repositoryUrl: "https://github.com/skerishKang/401-love-match-making",
    workspace: "/",
    pageUrl: null,
    stage: "planned",
    progressNote: "저장소 존재. 구현·배포 근거 없음.",
    currentWork: "현재 작업 없음",
    nextAction: "구현 범위 정의",
    lastVerified: "2026-07-25"
  },
  {
    id: "ai-finder-namgu",
    name: "광주 남구청 AI Finder",
    koreanName: "광주 남구청 AI 파인더",
    businessNumber: null,
    purpose: "광주 남구청 대상 AI 기반 정보 검색·안내 서비스입니다.",
    repositoryLabel: "확인 필요",
    repositoryUrl: null,
    workspace: "확인 필요",
    pageUrl: null,
    stage: "planned",
    progressNote: "구현·배포 근거 없음.",
    currentWork: "현재 작업 없음",
    nextAction: "저장소 및 구현 범위 정의",
    lastVerified: "2026-07-25"
  },
  {
    id: "ai-finder-seogu",
    name: "광주 서구청 AI Finder",
    koreanName: "광주 서구청 AI 파인더",
    businessNumber: null,
    purpose: "광주 서구청 대상 AI 기반 정보 검색·안내 서비스입니다.",
    repositoryLabel: "확인 필요",
    repositoryUrl: null,
    workspace: "확인 필요",
    pageUrl: null,
    stage: "planned",
    progressNote: "구현·배포 근거 없음.",
    currentWork: "현재 작업 없음",
    nextAction: "저장소 및 구현 범위 정의",
    lastVerified: "2026-07-25"
  }
];
