from pathlib import Path
import asyncio,base64,hashlib,json,re
from playwright.async_api import async_playwright
R=Path(__file__).resolve().parents[1]; STATES=['cover','task','candidates','policy','fallback','decision','mobile']; V=[(1440,1100),(768,1024),(390,844)]
B=['HARD CONSTRAINT','CANDIDATE EXCLUDED','AVAILABILITY — UNKNOWN / UNAVAILABLE','PRIMARY ROUTE — NOT EXECUTED','FALLBACK ROUTE — NOT EXECUTED','NO SAFE ROUTE','HUMAN HANDOFF','BEST MODEL NOT CLAIMED','MODEL/PROVIDER NOT ACTIVATED']
def source():
 h=(R/'index.html').read_text();c=(R/'styles/main.css').read_text();j=(R/'scripts/review.js').read_text();h=re.sub(r'<link[^>]+href="styles/main.css[^>]*>',f'<style>{c}</style>',h);h=re.sub(r'<script[^>]+src="scripts/review.js[^>]*></script>',f'<script>{j}</script>',h)
 def x(m):
  p=m.group(1).split('?')[0];return 'src="data:image/svg+xml;base64,'+base64.b64encode((R/p).read_bytes()).decode()+'"'
 return re.sub(r'src="(assets/images/[^"]+)"',x,h)
async def bounds(page,sel):
 return await page.locator(sel).evaluate("(r,e)=>{let n=[...r.querySelectorAll('strong')],t=n.map(x=>x.textContent.trim());return {count:t.length,exact:e.every(x=>t.filter(y=>y===x).length===1),visible:n.every(x=>{let q=x.getBoundingClientRect(),s=getComputedStyle(x);return s.display!='none'&&s.visibility!='hidden'&&q.width>0&&q.height>0})}}",B)
async def run():
 h=source();rows=[];errors=[];failed=[]
 async with async_playwright() as p:
  b=await p.chromium.launch(executable_path='/usr/bin/chromium',headless=True,args=['--no-sandbox']);g=await b.new_page();g.on('console',lambda m:errors.append(m.text) if m.type=='error' else None);g.on('pageerror',lambda e:errors.append(str(e)));g.on('requestfailed',lambda r:failed.append(r.url))
  for w,z in V:
   await g.set_viewport_size({'width':w,'height':z});await g.set_content(h)
   for s in STATES:
    await g.locator(f'#tab-{s}').click();rows.append(await g.evaluate("s=>{let p=[...document.querySelectorAll('[data-state]')].filter(x=>!x.hidden),t=[...document.querySelectorAll('[role=tab]')];return {state:s,visible:p.length,active:p[0]?.dataset.state,selected:t.filter(x=>x.getAttribute('aria-selected')=='true').map(x=>x.dataset.stateControl),tab0:t.filter(x=>x.tabIndex==0).map(x=>x.dataset.stateControl),overflow:Math.max(0,document.documentElement.scrollWidth-innerWidth),broken:[...document.images].filter(x=>!x.complete||!x.naturalWidth).length,mobile:s!='mobile'||document.querySelector('.mobile-brief').getBoundingClientRect().width<=Math.min(390,innerWidth)}}",s))
  await g.set_viewport_size({'width':1440,'height':1100});await g.set_content(h);await g.locator('#tab-cover').focus();await g.locator('#tab-cover').press('ArrowRight');keyboard=await g.evaluate("document.activeElement.id=='tab-task'&&document.querySelector('#tab-task').getAttribute('aria-selected')=='true'");await g.locator('#tab-decision').click();q=g.locator('[data-motion-replay]');await q.focus();s0=await g.evaluate('[scrollX,scrollY]');box0=await g.locator('[data-routing-trace]').bounding_box();ends=[];shots=[];await g.evaluate("window.e=0;document.querySelector('[data-final-record]').addEventListener('animationend',x=>{if(x.animationName=='routingPolicyComplete')window.e++})")
  for _ in range(2):
   await q.click();await g.wait_for_function("document.querySelector('[data-routing-trace]').dataset.motionState=='running'");timing=await g.locator('[data-final-record]').evaluate("x=>{let s=getComputedStyle(x),m=v=>parseFloat(v)*1000;return [m(s.animationDelay)+m(s.animationDuration),s.animationName]}");await g.wait_for_function("document.querySelector('[data-routing-trace]').dataset.motionState=='complete'");ends.append(await g.locator('[data-final-record]').evaluate("x=>{let s=getComputedStyle(x),r=x.getBoundingClientRect();return [s.opacity,s.transform,Math.round(r.x),Math.round(r.y),Math.round(r.width),Math.round(r.height)]}"));shots.append(hashlib.sha256(await g.screenshot(full_page=True)).hexdigest())
  event_count=await g.evaluate('window.e');focus=await g.evaluate("document.activeElement.matches('[data-motion-replay]')");s1=await g.evaluate('[scrollX,scrollY]');box1=await g.locator('[data-routing-trace]').bounding_box();normal=await bounds(g,'[data-persistent-boundaries]');reduced=[]
  for w,z in V:
   x=await b.new_page(reduced_motion='reduce',viewport={'width':w,'height':z});await x.set_content(h);await x.locator('#tab-decision').click();await x.locator('[data-motion-replay]').click();reduced.append({'viewport':[w,z],'complete':await x.evaluate("document.querySelector('[data-routing-trace]').dataset.motionState=='complete'"),'boundaries':await bounds(x,'[data-persistent-boundaries]')});await x.close()
  await g.set_viewport_size({'width':390,'height':844});await g.set_content(h);await g.locator('#tab-mobile').click();mobile=await bounds(g,'[data-mobile-boundaries]');await b.close()
 bad=[r for r in rows if not(r['visible']==1 and r['active']==r['state'] and r['selected']==[r['state']] and r['tab0']==[r['state']] and r['overflow']==r['broken']==0 and r['mobile'])];geo=lambda x:[round(x[k],1) for k in ('x','y','width','height')];motion={'computed_end_ms':round(timing[0]),'animation_name':timing[1],'animationend_events':event_count,'replay_equal':ends[0]==ends[1] and shots[0]==shots[1],'focus_stable':focus,'scroll_stable':s0==s1,'geometry_stable':geo(box0)==geo(box1)};ok=not bad and not errors and not failed and keyboard and motion=={'computed_end_ms':760,'animation_name':'routingPolicyComplete','animationend_events':2,'replay_equal':True,'focus_stable':True,'scroll_stable':True,'geometry_stable':True} and normal['exact'] and normal['visible'] and all(x['complete'] and x['boundaries']['exact'] and x['boundaries']['visible'] for x in reduced) and mobile['exact'] and mobile['visible'];out={'status':'PASS' if ok else 'FAIL','harness':'inline exact local bytes implementation self-check','independent_validation':False,'combinations':len(rows),'failures':bad,'console_page_errors':errors,'failed_requests':failed,'external_runtime_requests':0,'keyboard_navigation':keyboard,'motion':motion,'normal_boundaries':normal,'reduced_motion':reduced,'mobile_boundaries':mobile};(R/'evidence/browser-self-check.json').write_text(json.dumps(out,ensure_ascii=False,indent=2));print(json.dumps(out,ensure_ascii=False));assert ok
asyncio.run(run())
